"""Tests for the poller service."""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
from typing import Any
from unittest.mock import patch

import pytest

from franktheunicorn.backends.mock import MockGitHubClient
from franktheunicorn.backends.poller import _upsert_pull_request, poll_project
from franktheunicorn.config.models import ProjectConfig
from franktheunicorn.core.models import Project, PullRequest
from tests.factories import ProjectFactory, ReviewDraftFactory


@pytest.mark.django_db
class TestPoller:
    def test_poll_creates_project_and_prs(self, tmp_path: Any) -> None:
        client = MockGitHubClient(tmp_path)
        config = ProjectConfig(
            owner="apache",
            repo="spark",
            watched_paths=["sql/catalyst/"],
            frequent_contributors=["cloud-fan"],
        )
        prs = poll_project(client, config, operator_username="holdenk")
        assert len(prs) == 3
        assert Project.objects.filter(owner="apache", repo="spark").exists()
        assert PullRequest.objects.count() == 3

    def test_poll_updates_existing_prs(self, tmp_path: Any) -> None:
        """Polling twice should update, not duplicate."""
        client = MockGitHubClient(tmp_path)
        config = ProjectConfig(owner="apache", repo="spark")
        poll_project(client, config, operator_username="holdenk")
        poll_project(client, config, operator_username="holdenk")
        assert PullRequest.objects.count() == 3

    def test_poll_scores_prs(self, tmp_path: Any) -> None:
        client = MockGitHubClient(tmp_path)
        config = ProjectConfig(
            owner="apache",
            repo="spark",
            watched_paths=["sql/"],
        )
        prs = poll_project(client, config, operator_username="holdenk")
        # PR #42 has holdenk as requested reviewer, so should score > 0
        pr42 = next(p for p in prs if p.number == 42)
        assert pr42.interest_score > 0
        assert len(pr42.score_breakdown) > 0


@pytest.mark.django_db
class TestSessionDetectionInPoller:
    """Tests for v1.25 session link detection during PR ingestion."""

    def test_claude_code_session_detected(self) -> None:
        project = ProjectFactory(owner="test", repo="repo")
        pr_data = {
            "number": 1,
            "id": 2001,
            "title": "AI-generated fix",
            "user": {"login": "claude-bot"},
            "state": "open",
            "html_url": "https://github.com/test/repo/pull/1",
            "diff_url": "",
            "body": ("Generated by Claude Code\nSession: https://claude.ai/code/session/abc123\n"),
            "labels": [],
            "requested_reviewers": [],
            "assignees": [],
            "draft": False,
            "additions": 10,
            "deletions": 2,
            "created_at": "2026-03-30T10:00:00Z",
            "updated_at": "2026-03-30T10:00:00Z",
        }
        pr = _upsert_pull_request(project, pr_data, ["src/fix.py"])
        assert pr.ai_agent_source == "claude-code"
        assert pr.agent_session_url == "https://claude.ai/code/session/abc123"
        assert pr.agent_task_id == ""
        assert pr.likely_ai_generated is True

    def test_codex_task_detected(self) -> None:
        project = ProjectFactory(owner="test", repo="repo")
        pr_data = {
            "number": 2,
            "id": 2002,
            "title": "Codex fix",
            "user": {"login": "codex-bot"},
            "state": "open",
            "html_url": "https://github.com/test/repo/pull/2",
            "diff_url": "",
            "body": "Generated by Codex\nTask ID: task_xyz789\n",
            "labels": [],
            "requested_reviewers": [],
            "assignees": [],
            "draft": False,
            "additions": 5,
            "deletions": 1,
            "created_at": "2026-03-30T10:00:00Z",
            "updated_at": "2026-03-30T10:00:00Z",
        }
        pr = _upsert_pull_request(project, pr_data, [])
        assert pr.ai_agent_source == "codex"
        assert pr.agent_task_id == "task_xyz789"
        assert pr.likely_ai_generated is True

    def test_no_session_leaves_fields_empty(self) -> None:
        project = ProjectFactory(owner="test", repo="repo")
        pr_data = {
            "number": 3,
            "id": 2003,
            "title": "Normal PR",
            "user": {"login": "human-dev"},
            "state": "open",
            "html_url": "https://github.com/test/repo/pull/3",
            "diff_url": "",
            "body": "Just a normal PR fixing a bug.",
            "labels": [],
            "requested_reviewers": [],
            "assignees": [],
            "draft": False,
            "additions": 10,
            "deletions": 5,
            "created_at": "2026-03-30T10:00:00Z",
            "updated_at": "2026-03-30T10:00:00Z",
        }
        pr = _upsert_pull_request(project, pr_data, [])
        assert pr.ai_agent_source == ""
        assert pr.agent_session_url == ""
        assert pr.agent_task_id == ""

    def test_stale_session_fields_cleared_on_body_change(self) -> None:
        """If a PR body previously had a session link but now doesn't, fields are cleared."""
        project = ProjectFactory(owner="test", repo="repo")
        # First ingestion: has session link
        pr_data_with_session = {
            "number": 4,
            "id": 2004,
            "title": "AI PR",
            "user": {"login": "bot"},
            "state": "open",
            "html_url": "https://github.com/test/repo/pull/4",
            "diff_url": "",
            "body": "Session: https://claude.ai/code/session/abc123",
            "labels": [],
            "requested_reviewers": [],
            "assignees": [],
            "draft": False,
            "additions": 1,
            "deletions": 1,
            "created_at": "2026-03-30T10:00:00Z",
            "updated_at": "2026-03-30T10:00:00Z",
        }
        pr = _upsert_pull_request(project, pr_data_with_session, [])
        assert pr.ai_agent_source == "claude-code"
        assert pr.agent_session_url == "https://claude.ai/code/session/abc123"

        # Second ingestion: session link removed from body
        pr_data_without_session = {**pr_data_with_session, "body": "Updated PR description."}
        pr = _upsert_pull_request(project, pr_data_without_session, [])
        assert pr.ai_agent_source == ""
        assert pr.agent_session_url == ""
        assert pr.agent_task_id == ""


class _TrackingMockClient(MockGitHubClient):
    """MockGitHubClient that tracks get_issue_comments calls."""

    def __init__(
        self, fixtures_dir: str | Path, comments: list[dict[str, Any]] | None = None
    ) -> None:
        super().__init__(fixtures_dir)
        self.issue_comments_calls: list[tuple[str, str, int]] = []
        self._comments = comments or []

    def get_issue_comments(
        self, owner: str, repo: str, issue_number: int, since: str | None = None
    ) -> list[dict[str, Any]]:
        self.issue_comments_calls.append((owner, repo, issue_number))
        return self._comments


@pytest.mark.django_db
class TestReEngagementDataInPoller:
    def test_issue_comments_fetched_for_reviewed_pr(self, tmp_path: Any) -> None:
        """get_issue_comments is called for PRs with posted ReviewDrafts."""
        client = _TrackingMockClient(tmp_path)
        config = ProjectConfig(owner="apache", repo="spark")
        # First poll to create PRs
        prs = poll_project(client, config, operator_username="holdenk")
        pr42 = next(p for p in prs if p.number == 42)

        # Create a posted ReviewDraft for PR #42
        ReviewDraftFactory(
            pull_request=pr42,
            status="posted",
            posted_at=datetime(2026, 3, 25, tzinfo=UTC),
        )

        # Re-poll — should now fetch issue comments for PR #42
        client.issue_comments_calls.clear()
        poll_project(client, config, operator_username="holdenk")
        called_prs = [call[2] for call in client.issue_comments_calls]
        assert 42 in called_prs

    def test_issue_comments_not_fetched_for_unreviewed_pr(self, tmp_path: Any) -> None:
        """get_issue_comments is NOT called for PRs without posted ReviewDrafts."""
        client = _TrackingMockClient(tmp_path)
        config = ProjectConfig(owner="apache", repo="spark")
        poll_project(client, config, operator_username="holdenk")
        assert len(client.issue_comments_calls) == 0

    def test_author_replies_boost_score(self, tmp_path: Any) -> None:
        """PRs with author replies after operator review get higher scores."""
        # First poll without review data
        client_no_replies = _TrackingMockClient(tmp_path)
        config = ProjectConfig(owner="apache", repo="spark")
        prs = poll_project(client_no_replies, config, operator_username="holdenk")
        pr42 = next(p for p in prs if p.number == 42)
        score_without = pr42.interest_score

        # Add a posted review and author reply
        ReviewDraftFactory(
            pull_request=pr42,
            status="posted",
            posted_at=datetime(2026, 3, 25, tzinfo=UTC),
        )
        author_comments = [
            {
                "user": {"login": "alice-dev"},
                "created_at": "2026-03-27T10:00:00Z",
                "body": "Done, I addressed your feedback.",
            }
        ]
        client_with_replies = _TrackingMockClient(tmp_path, comments=author_comments)
        prs = poll_project(client_with_replies, config, operator_username="holdenk")
        pr42 = next(p for p in prs if p.number == 42)
        score_with = pr42.interest_score

        assert score_with > score_without
        assert "updated_since_operator_review" in pr42.score_breakdown
        assert "pending_response" in pr42.score_breakdown


# ---------------------------------------------------------------------------
# Helpers shared by TestPollerRefFetching
# ---------------------------------------------------------------------------

_BASE_SHA = "a" * 40
_HEAD_SHA = "b" * 40


def _make_pr_list_item() -> dict[str, Any]:
    return {
        "number": 99,
        "id": 9999,
        "title": "Test PR",
        "user": {"login": "test-user"},
        "state": "open",
        "html_url": "https://github.com/apache/spark/pull/99",
        "diff_url": "",
        "body": "",
        "labels": [],
        "requested_reviewers": [],
        "assignees": [],
        "draft": False,
        "additions": 5,
        "deletions": 2,
        "created_at": "2026-04-01T10:00:00Z",
        "updated_at": "2026-04-01T10:00:00Z",
    }


class _SinglePRMockClient(MockGitHubClient):
    """MockGitHubClient returning a single PR with a controlled detail dict."""

    def __init__(self, tmp_path: Path, pr_detail: dict[str, Any]) -> None:
        super().__init__(tmp_path)
        self._pr_detail = pr_detail

    def list_pull_requests(
        self, owner: str, repo: str, state: str = "open"
    ) -> list[dict[str, Any]]:
        return [_make_pr_list_item()]

    def get_pull_request(self, owner: str, repo: str, pr_number: int) -> dict[str, Any]:
        return self._pr_detail

    def get_pull_request_files(self, owner: str, repo: str, pr_number: int) -> list[dict[str, Any]]:
        return [{"filename": "src/main.py", "additions": 5, "deletions": 2, "status": "modified"}]


def _same_repo_detail(owner: str = "apache", repo: str = "spark") -> dict[str, Any]:
    """PR detail for a same-repo PR (no fork)."""
    return {
        "number": 99,
        "mergeable": True,
        "base": {
            "ref": "main",
            "sha": _BASE_SHA,
            "repo": {"full_name": f"{owner}/{repo}"},
        },
        "head": {
            "ref": "feature-branch",
            "sha": _HEAD_SHA,
            "repo": {
                "clone_url": f"https://github.com/{owner}/{repo}.git",
                "full_name": f"{owner}/{repo}",
                "fork": False,
            },
        },
    }


def _fork_detail(
    owner: str = "apache",
    repo: str = "spark",
    fork_clone_url: str = "https://github.com/fork-user/spark.git",
) -> dict[str, Any]:
    """PR detail for a cross-repo (fork) PR."""
    return {
        "number": 99,
        "mergeable": True,
        "base": {
            "ref": "main",
            "sha": _BASE_SHA,
            "repo": {"full_name": f"{owner}/{repo}"},
        },
        "head": {
            "ref": "fork-feature",
            "sha": _HEAD_SHA,
            "repo": {
                "clone_url": fork_clone_url,
                "full_name": "fork-user/spark",
                "fork": True,
            },
        },
    }


@pytest.mark.django_db
class TestPollerRefFetching:
    """Tests that the poller calls ensure_sha_fetched with the correct arguments."""

    def test_base_sha_fetch_attempted_when_missing(self, tmp_path: Path) -> None:
        """ensure_sha_fetched is called for the base SHA with branch and pr_number."""
        client = _SinglePRMockClient(tmp_path, _same_repo_detail())
        config = ProjectConfig(owner="apache", repo="spark")

        with patch(
            "franktheunicorn.worker.repo_manager.ensure_sha_fetched",
            return_value=False,
        ) as mock_fetch:
            poll_project(client, config, operator_username="holdenk", repo_path=tmp_path)

        base_calls = [c for c in mock_fetch.call_args_list if c.args[1] == _BASE_SHA]
        assert base_calls, "ensure_sha_fetched not called for base SHA"
        kw = base_calls[0].kwargs
        assert kw["branch"] == "main"
        assert kw["pr_number"] == 99

    def test_head_sha_fetch_attempted_for_fork(self, tmp_path: Path) -> None:
        """Fork URL is forwarded to ensure_sha_fetched for the head SHA."""
        fork_url = "https://github.com/fork-user/spark.git"
        client = _SinglePRMockClient(tmp_path, _fork_detail(fork_clone_url=fork_url))
        config = ProjectConfig(owner="apache", repo="spark")

        with patch(
            "franktheunicorn.worker.repo_manager.ensure_sha_fetched",
            return_value=False,
        ) as mock_fetch:
            poll_project(client, config, operator_username="holdenk", repo_path=tmp_path)

        head_calls = [c for c in mock_fetch.call_args_list if c.args[1] == _HEAD_SHA]
        assert head_calls, "ensure_sha_fetched not called for head SHA"
        kw = head_calls[0].kwargs
        assert kw["fork_clone_url"] == fork_url
        assert kw["pr_number"] == 99

    def test_blame_skipped_when_both_unavailable(self, tmp_path: Path) -> None:
        """fetch_blame_for_files is NOT called when ensure_sha_fetched returns False."""
        client = _SinglePRMockClient(tmp_path, _same_repo_detail())
        config = ProjectConfig(owner="apache", repo="spark")

        with (
            patch(
                "franktheunicorn.worker.repo_manager.ensure_sha_fetched",
                return_value=False,
            ),
            patch("franktheunicorn.scoring.blame_fetcher.fetch_blame_for_files") as mock_blame,
        ):
            poll_project(client, config, operator_username="holdenk", repo_path=tmp_path)

        mock_blame.assert_not_called()

    def test_blame_runs_when_both_available_after_fetch(self, tmp_path: Path) -> None:
        """fetch_blame_for_files IS called when ensure_sha_fetched returns True."""
        client = _SinglePRMockClient(tmp_path, _same_repo_detail())
        config = ProjectConfig(owner="apache", repo="spark")

        with (
            patch(
                "franktheunicorn.worker.repo_manager.ensure_sha_fetched",
                return_value=True,
            ),
            patch(
                "franktheunicorn.scoring.blame_fetcher.fetch_blame_for_files",
                return_value=[],
            ) as mock_blame,
        ):
            poll_project(client, config, operator_username="holdenk", repo_path=tmp_path)

        mock_blame.assert_called_once()
