"""Tests for the poller service."""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any
from unittest.mock import patch

import pytest
from django.utils import timezone

from franktheunicorn.backends.base import MAX_LISTED_PULL_REQUESTS
from franktheunicorn.backends.mock import MockGitHubClient
from franktheunicorn.backends.poller import _upsert_pull_request, poll_project
from franktheunicorn.config.models import ProjectConfig
from franktheunicorn.core.models import Project, PullRequest
from tests.factories import ProjectFactory, ReviewDraftFactory


@pytest.mark.django_db
class TestPoller:
    def test_poll_creates_project_and_prs(self, tmp_path: Any) -> None:
        client = MockGitHubClient(tmp_path)
        config = ProjectConfig(
            owner="apache",
            repo="spark",
            watched_paths=["sql/catalyst/"],
            frequent_contributors=["cloud-fan"],
        )
        prs = poll_project(client, config, operator_username="holdenk")
        assert len(prs) == 3
        assert Project.objects.filter(owner="apache", repo="spark").exists()
        assert PullRequest.objects.count() == 3

    def test_poll_updates_existing_prs(self, tmp_path: Any) -> None:
        """Polling twice should update, not duplicate."""
        client = MockGitHubClient(tmp_path)
        config = ProjectConfig(owner="apache", repo="spark")
        poll_project(client, config, operator_username="holdenk")
        poll_project(client, config, operator_username="holdenk")
        assert PullRequest.objects.count() == 3

    def test_poll_scores_prs(self, tmp_path: Any) -> None:
        client = MockGitHubClient(tmp_path)
        config = ProjectConfig(
            owner="apache",
            repo="spark",
            watched_paths=["sql/"],
        )
        prs = poll_project(client, config, operator_username="holdenk")
        # PR #42 has holdenk as requested reviewer, so should score > 0
        pr42 = next(p for p in prs if p.number == 42)
        assert pr42.interest_score > 0
        assert len(pr42.score_breakdown) > 0


@pytest.mark.django_db
class TestSessionDetectionInPoller:
    """Tests for v1.25 session link detection during PR ingestion."""

    def test_claude_code_session_detected(self) -> None:
        project = ProjectFactory(owner="test", repo="repo")
        pr_data = {
            "number": 1,
            "id": 2001,
            "title": "AI-generated fix",
            "user": {"login": "claude-bot"},
            "state": "open",
            "html_url": "https://github.com/test/repo/pull/1",
            "diff_url": "",
            "body": ("Generated by Claude Code\nSession: https://claude.ai/code/session/abc123\n"),
            "labels": [],
            "requested_reviewers": [],
            "assignees": [],
            "draft": False,
            "additions": 10,
            "deletions": 2,
            "created_at": "2026-03-30T10:00:00Z",
            "updated_at": "2026-03-30T10:00:00Z",
        }
        pr = _upsert_pull_request(project, pr_data, ["src/fix.py"])
        assert pr.ai_agent_source == "claude-code"
        assert pr.agent_session_url == "https://claude.ai/code/session/abc123"
        assert pr.agent_task_id == ""
        assert pr.likely_ai_generated is True

    def test_codex_task_detected(self) -> None:
        project = ProjectFactory(owner="test", repo="repo")
        pr_data = {
            "number": 2,
            "id": 2002,
            "title": "Codex fix",
            "user": {"login": "codex-bot"},
            "state": "open",
            "html_url": "https://github.com/test/repo/pull/2",
            "diff_url": "",
            "body": "Generated by Codex\nTask ID: task_xyz789\n",
            "labels": [],
            "requested_reviewers": [],
            "assignees": [],
            "draft": False,
            "additions": 5,
            "deletions": 1,
            "created_at": "2026-03-30T10:00:00Z",
            "updated_at": "2026-03-30T10:00:00Z",
        }
        pr = _upsert_pull_request(project, pr_data, [])
        assert pr.ai_agent_source == "codex"
        assert pr.agent_task_id == "task_xyz789"
        assert pr.likely_ai_generated is True

    def test_no_session_leaves_fields_empty(self) -> None:
        project = ProjectFactory(owner="test", repo="repo")
        pr_data = {
            "number": 3,
            "id": 2003,
            "title": "Normal PR",
            "user": {"login": "human-dev"},
            "state": "open",
            "html_url": "https://github.com/test/repo/pull/3",
            "diff_url": "",
            "body": "Just a normal PR fixing a bug.",
            "labels": [],
            "requested_reviewers": [],
            "assignees": [],
            "draft": False,
            "additions": 10,
            "deletions": 5,
            "created_at": "2026-03-30T10:00:00Z",
            "updated_at": "2026-03-30T10:00:00Z",
        }
        pr = _upsert_pull_request(project, pr_data, [])
        assert pr.ai_agent_source == ""
        assert pr.agent_session_url == ""
        assert pr.agent_task_id == ""

    def test_stale_session_fields_cleared_on_body_change(self) -> None:
        """If a PR body previously had a session link but now doesn't, fields are cleared."""
        project = ProjectFactory(owner="test", repo="repo")
        # First ingestion: has session link
        pr_data_with_session = {
            "number": 4,
            "id": 2004,
            "title": "AI PR",
            "user": {"login": "bot"},
            "state": "open",
            "html_url": "https://github.com/test/repo/pull/4",
            "diff_url": "",
            "body": "Session: https://claude.ai/code/session/abc123",
            "labels": [],
            "requested_reviewers": [],
            "assignees": [],
            "draft": False,
            "additions": 1,
            "deletions": 1,
            "created_at": "2026-03-30T10:00:00Z",
            "updated_at": "2026-03-30T10:00:00Z",
        }
        pr = _upsert_pull_request(project, pr_data_with_session, [])
        assert pr.ai_agent_source == "claude-code"
        assert pr.agent_session_url == "https://claude.ai/code/session/abc123"

        # Second ingestion: session link removed from body
        pr_data_without_session = {**pr_data_with_session, "body": "Updated PR description."}
        pr = _upsert_pull_request(project, pr_data_without_session, [])
        assert pr.ai_agent_source == ""
        assert pr.agent_session_url == ""
        assert pr.agent_task_id == ""


@pytest.mark.django_db
class TestDegradedFetchDoesNotClobber:
    """A rate-limit window (scrape fallback / failed files fetch) must not
    gut a PR that was already fully ingested from the API."""

    def _full_pr_data(self, number: int = 7) -> dict[str, Any]:
        return {
            "number": number,
            "id": 900000 + number,
            "title": "Real title",
            "user": {"login": "alice"},
            "state": "open",
            "html_url": f"https://github.com/test/repo/pull/{number}",
            "diff_url": "",
            "body": "The full PR description with detail.",
            "labels": [{"name": "bug"}, {"name": "tests"}],
            "requested_reviewers": [{"login": "holdenk"}],
            "assignees": [{"login": "bob"}],
            "draft": False,
            "additions": 120,
            "deletions": 30,
            "created_at": "2026-03-30T10:00:00Z",
            "updated_at": "2026-03-30T10:00:00Z",
        }

    def test_scraped_record_preserves_existing_rich_fields(self) -> None:
        project = ProjectFactory(owner="test", repo="repo")
        # First: a healthy API ingest with full data.
        _upsert_pull_request(project, self._full_pr_data(), ["src/a.py", "src/b.py"])

        # Then: a degraded scrape record (only number/title/author/state/url).
        scraped = {
            "_scraped": True,
            "number": 7,
            "id": 0,
            "title": "Real title (from scrape)",
            "user": {"login": "alice"},
            "state": "open",
            "html_url": "https://github.com/test/repo/pull/7",
            "diff_url": "",
            "body": "",
            "labels": [],
            "requested_reviewers": [],
            "assignees": [],
            "draft": False,
            "additions": 0,
            "deletions": 0,
            "created_at": "",
            "updated_at": "",
        }
        pr = _upsert_pull_request(project, scraped, None)

        # Refreshed field updates; rich fields preserved (not zeroed).
        assert pr.title == "Real title (from scrape)"
        assert pr.body == "The full PR description with detail."
        assert pr.labels == ["bug", "tests"]
        assert pr.additions == 120
        assert pr.deletions == 30
        assert pr.github_id == 900007  # real id not overwritten with 0
        assert pr.changed_files == ["src/a.py", "src/b.py"]
        assert pr.github_created_at is not None

    def test_none_changed_files_preserves_existing_list(self) -> None:
        project = ProjectFactory(owner="test", repo="repo")
        _upsert_pull_request(project, self._full_pr_data(8), ["src/x.py"])
        # A later cycle where the files fetch failed (None, not []).
        pr = _upsert_pull_request(project, self._full_pr_data(8), None)
        assert pr.changed_files == ["src/x.py"]

    def test_scraped_new_pr_is_created_minimally(self) -> None:
        project = ProjectFactory(owner="test", repo="repo")
        scraped = {
            "_scraped": True,
            "number": 99,
            "id": 0,
            "title": "New scraped PR",
            "user": {"login": "carol"},
            "state": "open",
            "html_url": "https://github.com/test/repo/pull/99",
            "diff_url": "",
            "body": "",
            "labels": [],
            "requested_reviewers": [],
            "assignees": [],
            "draft": False,
            "additions": 0,
            "deletions": 0,
            "created_at": "",
            "updated_at": "",
        }
        pr = _upsert_pull_request(project, scraped, None)
        assert pr.pk is not None
        assert pr.title == "New scraped PR"
        assert pr.changed_files == []


class _TrackingMockClient(MockGitHubClient):
    """MockGitHubClient that tracks get_issue_comments calls."""

    def __init__(
        self,
        fixtures_dir: str | Path,
        comments: list[dict[str, Any]] | None = None,
        updated_at: str | None = None,
    ) -> None:
        super().__init__(fixtures_dir)
        self.issue_comments_calls: list[tuple[str, str, int]] = []
        self._comments = comments or []
        # Upstream ``updated_at`` for every listed PR. Anything that happens on
        # a PR — a comment, a push, a reviewer change — bumps this on the forge
        # (checked against apache/spark#57960, whose updated_at equals its last
        # comment's timestamp), and that bump is what makes the poller spend
        # per-PR API calls on an already-ingested PR.
        self.updated_at = updated_at

    def list_pull_requests(
        self, owner: str, repo: str, state: str = "open"
    ) -> list[dict[str, Any]]:
        prs = super().list_pull_requests(owner, repo, state)
        if self.updated_at is not None:
            for pr_data in prs:
                pr_data["updated_at"] = self.updated_at
        return prs

    def get_issue_comments(
        self, owner: str, repo: str, issue_number: int, since: str | None = None
    ) -> list[dict[str, Any]]:
        self.issue_comments_calls.append((owner, repo, issue_number))
        return self._comments


def _pr_data(number: int, author: str) -> dict[str, Any]:
    return {
        "number": number,
        "id": 800000 + number,
        "title": f"Fix issue {number}",
        "user": {"login": author},
        "state": "open",
        "html_url": f"https://github.com/fighthealthinsurance/fighthealthinsurance/pull/{number}",
        "diff_url": "",
        "body": "This PR fixes a concrete issue with enough context for review.",
        "labels": [{"name": "bug"}],
        "requested_reviewers": [],
        "assignees": [],
        "draft": False,
        "additions": 4,
        "deletions": 1,
        "created_at": "2026-03-30T10:00:00Z",
        "updated_at": "2026-03-30T10:00:00Z",
    }


class _ContributorDetectionClient(MockGitHubClient):
    """Mock client with controlled PR ordering and contributor fetch behavior."""

    def __init__(
        self,
        tmp_path: Path,
        pull_requests: list[dict[str, Any]],
        contributors: list[str] | Exception,
    ) -> None:
        super().__init__(tmp_path)
        self._pull_requests = pull_requests
        self._contributors = contributors

    def list_pull_requests(
        self, owner: str, repo: str, state: str = "open"
    ) -> list[dict[str, Any]]:
        return self._pull_requests

    def get_pull_request_files(self, owner: str, repo: str, pr_number: int) -> list[dict[str, Any]]:
        return [{"filename": "src/app.py", "additions": 4, "deletions": 1, "status": "modified"}]

    def list_contributors(self, owner: str, repo: str) -> list[str]:
        if isinstance(self._contributors, Exception):
            raise self._contributors
        return self._contributors


@pytest.mark.django_db
class TestNewContributorDetection:
    def test_newest_first_empty_cache_multiple_prs_is_not_new(self, tmp_path: Path) -> None:
        """A newest-first batch must not latch one PR by an established local author as new."""
        client = _ContributorDetectionClient(
            tmp_path,
            [_pr_data(884, "nyghtowl"), _pr_data(870, "nyghtowl")],
            contributors=[],
        )
        config = ProjectConfig(owner="fighthealthinsurance", repo="fighthealthinsurance")

        poll_project(client, config, operator_username="holdenk")

        prs = PullRequest.objects.order_by("number")
        assert [pr.number for pr in prs] == [870, 884]
        assert all(not pr.is_new_contributor for pr in prs)
        assert all(pr.queue != "new-contributor" for pr in prs)
        project = Project.objects.get(owner="fighthealthinsurance", repo="fighthealthinsurance")
        assert project.contributors_cache == []
        assert project.contributors_cache_status == "empty"

    def test_failed_contributor_fetch_does_not_mark_new(self, tmp_path: Path) -> None:
        client = _ContributorDetectionClient(
            tmp_path,
            [_pr_data(884, "nyghtowl")],
            contributors=RuntimeError("contributors unavailable"),
        )
        config = ProjectConfig(owner="fighthealthinsurance", repo="fighthealthinsurance")

        [pr] = poll_project(client, config, operator_username="holdenk")

        pr.refresh_from_db()
        assert pr.is_new_contributor is False
        assert pr.queue != "new-contributor"
        project = Project.objects.get(owner="fighthealthinsurance", repo="fighthealthinsurance")
        assert project.contributors_cache == []
        assert project.contributors_cache_status == "failed"

    def test_positive_first_time_contributor_still_flags_new(self, tmp_path: Path) -> None:
        client = _ContributorDetectionClient(
            tmp_path,
            [_pr_data(12, "first-timer")],
            contributors=["established-dev"],
        )
        config = ProjectConfig(owner="fighthealthinsurance", repo="fighthealthinsurance")

        [pr] = poll_project(client, config, operator_username="holdenk")

        pr.refresh_from_db()
        assert pr.is_new_contributor is True
        assert pr.queue == "new-contributor"
        project = Project.objects.get(owner="fighthealthinsurance", repo="fighthealthinsurance")
        assert project.contributors_cache == ["established-dev"]
        assert project.contributors_cache_status == "fetched"


def _mentioned_pr_data(
    number: int,
    author: str,
    *,
    reviewers: list[str] | None = None,
    assignees: list[str] | None = None,
    body: str | None = None,
) -> dict[str, Any]:
    """PR list item with operator-involvement fields for mention-routing tests."""
    data = _pr_data(number, author)
    data["requested_reviewers"] = [{"login": r} for r in (reviewers or [])]
    data["assignees"] = [{"login": a} for a in (assignees or [])]
    if body is not None:
        data["body"] = body
    return data


@pytest.mark.django_db
class TestMentionedRouting:
    """PART A: operator-involvement routes a PR to the 'mentioned' queue."""

    def _poll_one(
        self, tmp_path: Path, pr_data: dict[str, Any], operator: str = "holdenk"
    ) -> PullRequest:
        # Seed contributors with the author so an uninvolved PR isn't sidetracked
        # into the new-contributor queue (isolates mention routing).
        client = _ContributorDetectionClient(
            tmp_path, [pr_data], contributors=[pr_data["user"]["login"]]
        )
        config = ProjectConfig(owner="apache", repo="spark")
        [pr] = poll_project(client, config, operator_username=operator)
        pr.refresh_from_db()
        return pr

    def test_requested_reviewer_routes_to_mentioned(self, tmp_path: Path) -> None:
        pr = self._poll_one(tmp_path, _mentioned_pr_data(101, "alice", reviewers=["holdenk"]))
        assert pr.is_mentioned is True
        assert pr.queue == "mentioned"

    def test_assignee_routes_to_mentioned(self, tmp_path: Path) -> None:
        pr = self._poll_one(tmp_path, _mentioned_pr_data(102, "alice", assignees=["holdenk"]))
        assert pr.is_mentioned is True
        assert pr.queue == "mentioned"

    def test_body_mention_routes_to_mentioned(self, tmp_path: Path) -> None:
        pr = self._poll_one(
            tmp_path,
            _mentioned_pr_data(
                103, "alice", body="ping @holdenk please review this substantial change"
            ),
        )
        assert pr.is_mentioned is True
        assert pr.queue == "mentioned"

    def test_uninvolved_pr_not_mentioned(self, tmp_path: Path) -> None:
        pr = self._poll_one(tmp_path, _mentioned_pr_data(104, "alice", reviewers=["bob"]))
        assert pr.is_mentioned is False
        assert pr.queue != "mentioned"

    def test_operator_pr_outranks_mentioned(self, tmp_path: Path) -> None:
        # Operator authored AND is a requested reviewer: your-prs wins.
        pr = self._poll_one(tmp_path, _mentioned_pr_data(105, "holdenk", reviewers=["holdenk"]))
        assert pr.is_operator_pr is True
        assert pr.queue == "your-prs"

    def test_mentioned_outranks_new_contributor(self, tmp_path: Path) -> None:
        # A brand-new contributor who also @-requests the operator → mentioned wins.
        client = _ContributorDetectionClient(
            tmp_path,
            [_mentioned_pr_data(106, "first-timer", reviewers=["holdenk"])],
            contributors=["established-dev"],
        )
        config = ProjectConfig(owner="apache", repo="spark")
        [pr] = poll_project(client, config, operator_username="holdenk")
        pr.refresh_from_db()
        assert pr.is_new_contributor is True
        assert pr.is_mentioned is True
        assert pr.queue == "mentioned"

    def test_is_mentioned_persisted_to_db(self, tmp_path: Path) -> None:
        # Prove the flag survives to the DB (poll_project's save writes it).
        pr = self._poll_one(tmp_path, _mentioned_pr_data(107, "alice", assignees=["holdenk"]))
        fresh = PullRequest.objects.get(pk=pr.pk)
        assert fresh.is_mentioned is True
        assert fresh.queue == "mentioned"

    def test_is_mentioned_cleared_when_involvement_removed(self, tmp_path: Path) -> None:
        # Re-poll after the operator is dropped as reviewer: flag/queue reset.
        # Exercises the reroute save path (state changes between polls).
        client = _ContributorDetectionClient(
            tmp_path,
            [_mentioned_pr_data(108, "alice", reviewers=["holdenk"])],
            contributors=["alice"],
        )
        config = ProjectConfig(owner="apache", repo="spark")
        [pr] = poll_project(client, config, operator_username="holdenk")
        assert pr.is_mentioned is True and pr.queue == "mentioned"

        client._pull_requests = [_mentioned_pr_data(108, "alice", reviewers=["bob"])]
        [pr] = poll_project(client, config, operator_username="holdenk")
        fresh = PullRequest.objects.get(pk=pr.pk)
        assert fresh.is_mentioned is False
        assert fresh.queue != "mentioned"


@pytest.mark.django_db
class TestReEngagementDataInPoller:
    def test_issue_comments_fetched_for_reviewed_pr(self, tmp_path: Any) -> None:
        """get_issue_comments is called for PRs with posted ReviewDrafts."""
        client = _TrackingMockClient(tmp_path)
        config = ProjectConfig(owner="apache", repo="spark")
        # First poll to create PRs
        prs = poll_project(client, config, operator_username="holdenk")
        pr42 = next(p for p in prs if p.number == 42)

        # Create a posted ReviewDraft for PR #42
        ReviewDraftFactory(
            pull_request=pr42,
            status="posted",
            posted_at=datetime(2026, 3, 25, tzinfo=UTC),
        )

        # Re-poll — should now fetch issue comments for PR #42. The review
        # posting bumped the PR upstream, so it's no longer "unchanged".
        client.issue_comments_calls.clear()
        client.updated_at = "2026-03-26T10:00:00Z"
        poll_project(client, config, operator_username="holdenk")
        called_prs = [call[2] for call in client.issue_comments_calls]
        assert 42 in called_prs

    def test_issue_comments_fetched_for_all_prs(self, tmp_path: Any) -> None:
        """get_issue_comments is called for every PR (needed for @mention scoring)."""
        client = _TrackingMockClient(tmp_path)
        config = ProjectConfig(owner="apache", repo="spark")
        prs = poll_project(client, config, operator_username="holdenk")
        # Comments are always fetched now so @mention scoring works even before
        # the operator has posted a review.
        assert len(client.issue_comments_calls) == len(prs)

    def test_author_replies_boost_score(self, tmp_path: Any) -> None:
        """PRs with author replies after operator review get higher scores."""
        # First poll without review data
        client_no_replies = _TrackingMockClient(tmp_path)
        config = ProjectConfig(owner="apache", repo="spark")
        prs = poll_project(client_no_replies, config, operator_username="holdenk")
        pr42 = next(p for p in prs if p.number == 42)
        score_without = pr42.interest_score

        # Add a posted review and author reply
        ReviewDraftFactory(
            pull_request=pr42,
            status="posted",
            posted_at=datetime(2026, 3, 25, tzinfo=UTC),
        )
        author_comments = [
            {
                "user": {"login": "alice-dev"},
                "created_at": "2026-03-27T10:00:00Z",
                "body": "Done, I addressed your feedback.",
            }
        ]
        # The author's reply bumps the PR upstream, which is what earns it a
        # re-poll.
        client_with_replies = _TrackingMockClient(
            tmp_path, comments=author_comments, updated_at="2026-03-27T10:00:00Z"
        )
        prs = poll_project(client_with_replies, config, operator_username="holdenk")
        pr42 = next(p for p in prs if p.number == 42)
        score_with = pr42.interest_score

        assert score_with > score_without
        assert "updated_since_operator_review" in pr42.score_breakdown
        assert "pending_response" in pr42.score_breakdown


# ---------------------------------------------------------------------------
# Helpers shared by TestPollerRefFetching
# ---------------------------------------------------------------------------

_BASE_SHA = "a" * 40
_HEAD_SHA = "b" * 40


def _make_pr_list_item() -> dict[str, Any]:
    return {
        "number": 99,
        "id": 9999,
        "title": "Test PR",
        "user": {"login": "test-user"},
        "state": "open",
        "html_url": "https://github.com/apache/spark/pull/99",
        "diff_url": "",
        "body": "",
        "labels": [],
        "requested_reviewers": [],
        "assignees": [],
        "draft": False,
        # The real GET /repos/{o}/{r}/pulls listing carries no diff stats —
        # those only come from the single-PR detail endpoint. Keep the fixture
        # honest so the detail-sourced repair stays under test.
        "created_at": "2026-04-01T10:00:00Z",
        "updated_at": "2026-04-01T10:00:00Z",
    }


class _SinglePRMockClient(MockGitHubClient):
    """MockGitHubClient returning a single PR with a controlled detail dict."""

    def __init__(self, tmp_path: Path, pr_detail: dict[str, Any]) -> None:
        super().__init__(tmp_path)
        self._pr_detail = pr_detail

    def list_pull_requests(
        self, owner: str, repo: str, state: str = "open"
    ) -> list[dict[str, Any]]:
        return [_make_pr_list_item()]

    def get_pull_request(self, owner: str, repo: str, pr_number: int) -> dict[str, Any]:
        return self._pr_detail

    def get_pull_request_files(self, owner: str, repo: str, pr_number: int) -> list[dict[str, Any]]:
        return [{"filename": "src/main.py", "additions": 5, "deletions": 2, "status": "modified"}]


def _same_repo_detail(owner: str = "apache", repo: str = "spark") -> dict[str, Any]:
    """PR detail for a same-repo PR (no fork)."""
    return {
        "number": 99,
        "mergeable": True,
        "base": {
            "ref": "main",
            "sha": _BASE_SHA,
            "repo": {"full_name": f"{owner}/{repo}"},
        },
        "head": {
            "ref": "feature-branch",
            "sha": _HEAD_SHA,
            "repo": {
                "clone_url": f"https://github.com/{owner}/{repo}.git",
                "full_name": f"{owner}/{repo}",
                "fork": False,
            },
        },
    }


def _fork_detail(
    owner: str = "apache",
    repo: str = "spark",
    fork_clone_url: str = "https://github.com/fork-user/spark.git",
) -> dict[str, Any]:
    """PR detail for a cross-repo (fork) PR."""
    return {
        "number": 99,
        "mergeable": True,
        "base": {
            "ref": "main",
            "sha": _BASE_SHA,
            "repo": {"full_name": f"{owner}/{repo}"},
        },
        "head": {
            "ref": "fork-feature",
            "sha": _HEAD_SHA,
            "repo": {
                "clone_url": fork_clone_url,
                "full_name": "fork-user/spark",
                "fork": True,
            },
        },
    }


@pytest.mark.django_db
class TestPollerRefFetching:
    """Tests that the poller calls ensure_sha_fetched with the correct arguments."""

    def test_base_sha_fetch_attempted_when_missing(self, tmp_path: Path) -> None:
        """ensure_sha_fetched is called for the base SHA with branch and pr_number."""
        client = _SinglePRMockClient(tmp_path, _same_repo_detail())
        config = ProjectConfig(owner="apache", repo="spark")

        with patch(
            "franktheunicorn.worker.repo_manager.ensure_sha_fetched",
            return_value=False,
        ) as mock_fetch:
            poll_project(client, config, operator_username="holdenk", repo_path=tmp_path)

        base_calls = [c for c in mock_fetch.call_args_list if c.args[1] == _BASE_SHA]
        assert base_calls, "ensure_sha_fetched not called for base SHA"
        kw = base_calls[0].kwargs
        assert kw["branch"] == "main"
        assert kw["pr_number"] == 99

    def test_head_sha_fetch_attempted_for_fork(self, tmp_path: Path) -> None:
        """Fork URL is forwarded to ensure_sha_fetched for the head SHA."""
        fork_url = "https://github.com/fork-user/spark.git"
        client = _SinglePRMockClient(tmp_path, _fork_detail(fork_clone_url=fork_url))
        config = ProjectConfig(owner="apache", repo="spark")

        with patch(
            "franktheunicorn.worker.repo_manager.ensure_sha_fetched",
            return_value=False,
        ) as mock_fetch:
            poll_project(client, config, operator_username="holdenk", repo_path=tmp_path)

        head_calls = [c for c in mock_fetch.call_args_list if c.args[1] == _HEAD_SHA]
        assert head_calls, "ensure_sha_fetched not called for head SHA"
        kw = head_calls[0].kwargs
        assert kw["fork_clone_url"] == fork_url
        assert kw["pr_number"] == 99

    def test_blame_skipped_when_both_unavailable(self, tmp_path: Path) -> None:
        """fetch_blame_for_files is NOT called when ensure_sha_fetched returns False."""
        client = _SinglePRMockClient(tmp_path, _same_repo_detail())
        config = ProjectConfig(owner="apache", repo="spark")

        with (
            patch(
                "franktheunicorn.worker.repo_manager.ensure_sha_fetched",
                return_value=False,
            ),
            patch("franktheunicorn.scoring.blame_fetcher.fetch_blame_for_files") as mock_blame,
        ):
            poll_project(client, config, operator_username="holdenk", repo_path=tmp_path)

        mock_blame.assert_not_called()

    def test_blame_runs_when_both_available_after_fetch(self, tmp_path: Path) -> None:
        """fetch_blame_for_files IS called when ensure_sha_fetched returns True."""
        client = _SinglePRMockClient(tmp_path, _same_repo_detail())
        config = ProjectConfig(owner="apache", repo="spark")

        with (
            patch(
                "franktheunicorn.worker.repo_manager.ensure_sha_fetched",
                return_value=True,
            ),
            patch(
                "franktheunicorn.scoring.blame_fetcher.fetch_blame_for_files",
                return_value=[],
            ) as mock_blame,
        ):
            poll_project(client, config, operator_username="holdenk", repo_path=tmp_path)

        mock_blame.assert_called_once()


class _CountingMockClient(MockGitHubClient):
    """Mock client that counts per-PR API calls and lets the listing be edited.

    Declares a complete listing: its pr_list is the whole truth, which is what
    the closed-PR reap requires. Clients that return one short page (Gitea,
    GitLab) must not set this.
    """

    lists_all_open_pull_requests = True

    def __init__(self, tmp_path: Path, pr_list: list[dict[str, Any]]) -> None:
        super().__init__(tmp_path)
        self.pr_list = pr_list
        self.detail_calls: list[int] = []
        self.files_calls: list[int] = []

    def list_pull_requests(
        self, owner: str, repo: str, state: str = "open"
    ) -> list[dict[str, Any]]:
        return self.pr_list

    def get_pull_request(self, owner: str, repo: str, pr_number: int) -> dict[str, Any]:
        self.detail_calls.append(pr_number)
        return _same_repo_detail() | {"number": pr_number, "additions": 31, "deletions": 7}

    def get_pull_request_files(self, owner: str, repo: str, pr_number: int) -> list[dict[str, Any]]:
        self.files_calls.append(pr_number)
        return [{"filename": "src/main.py", "additions": 5, "deletions": 2, "status": "modified"}]


def _listed_pr(number: int = 99, **overrides: Any) -> dict[str, Any]:
    return _make_pr_list_item() | {"number": number} | overrides


@pytest.mark.django_db
class TestUnchangedPRSkip:
    """An untouched PR must not cost per-PR API calls on every cycle."""

    def _config(self, **overrides: Any) -> ProjectConfig:
        return ProjectConfig(owner="apache", repo="spark", **overrides)

    def test_second_poll_skips_unchanged_pr(self, tmp_path: Path) -> None:
        client = _CountingMockClient(tmp_path, [_listed_pr()])
        config = self._config()

        assert len(poll_project(client, config, operator_username="holdenk")) == 1
        assert client.detail_calls == [99]

        client.detail_calls.clear()
        client.files_calls.clear()
        assert poll_project(client, config, operator_username="holdenk") == []
        assert client.detail_calls == []
        assert client.files_calls == []
        # The row is still there and still open — skipped, not dropped.
        assert PullRequest.objects.filter(number=99, state="open").count() == 1

    def test_upstream_update_triggers_refresh(self, tmp_path: Path) -> None:
        client = _CountingMockClient(tmp_path, [_listed_pr()])
        config = self._config()
        poll_project(client, config, operator_username="holdenk")

        client.detail_calls.clear()
        client.pr_list = [_listed_pr(updated_at="2026-04-02T11:00:00Z")]
        assert len(poll_project(client, config, operator_username="holdenk")) == 1
        assert client.detail_calls == [99]

    def test_reviewer_change_triggers_refresh_without_timestamp_bump(self, tmp_path: Path) -> None:
        """Routing-relevant listing fields are compared, not just updated_at."""
        client = _CountingMockClient(tmp_path, [_listed_pr()])
        config = self._config()
        poll_project(client, config, operator_username="holdenk")

        client.detail_calls.clear()
        client.pr_list = [_listed_pr(requested_reviewers=[{"login": "holdenk"}])]
        assert len(poll_project(client, config, operator_username="holdenk")) == 1
        assert client.detail_calls == [99]

    def test_label_and_title_changes_trigger_refresh(self, tmp_path: Path) -> None:
        client = _CountingMockClient(tmp_path, [_listed_pr()])
        config = self._config()
        poll_project(client, config, operator_username="holdenk")

        client.detail_calls.clear()
        client.pr_list = [_listed_pr(title="Test PR (now WIP)", labels=[{"name": "SQL"}])]
        assert len(poll_project(client, config, operator_username="holdenk")) == 1
        assert client.detail_calls == [99]

    def test_zero_refresh_hours_disables_skip(self, tmp_path: Path) -> None:
        client = _CountingMockClient(tmp_path, [_listed_pr()])
        config = self._config(poll_refresh_hours=0)
        poll_project(client, config, operator_username="holdenk")

        client.detail_calls.clear()
        assert len(poll_project(client, config, operator_username="holdenk")) == 1
        assert client.detail_calls == [99]

    def test_stale_local_refresh_forces_reprocess(self, tmp_path: Path) -> None:
        """Time-dependent signals get re-scored once the refresh window lapses."""
        client = _CountingMockClient(tmp_path, [_listed_pr()])
        config = self._config(poll_refresh_hours=24)
        poll_project(client, config, operator_username="holdenk")

        PullRequest.objects.filter(number=99).update(
            last_polled_at=timezone.now() - timedelta(days=3)
        )
        client.detail_calls.clear()
        assert len(poll_project(client, config, operator_username="holdenk")) == 1
        assert client.detail_calls == [99]

    def test_degraded_row_is_refreshed(self, tmp_path: Path) -> None:
        """A row left without a base SHA by an interrupted cycle gets finished."""
        client = _CountingMockClient(tmp_path, [_listed_pr()])
        config = self._config()
        poll_project(client, config, operator_username="holdenk")

        PullRequest.objects.filter(number=99).update(base_sha="")
        client.detail_calls.clear()
        assert len(poll_project(client, config, operator_username="holdenk")) == 1
        assert client.detail_calls == [99]

    def test_diff_stats_come_from_detail(self, tmp_path: Path) -> None:
        """The listing has no additions/deletions; the detail response does."""
        client = _CountingMockClient(tmp_path, [_listed_pr()])
        poll_project(client, ProjectConfig(owner="apache", repo="spark"), "holdenk")

        pr = PullRequest.objects.get(number=99)
        assert (pr.additions, pr.deletions) == (31, 7)

    def test_failed_detail_fetch_keeps_existing_diff_stats(self, tmp_path: Path) -> None:
        """A rate-limited detail call must not zero stats we already had.

        The listing carries no diff stats, so writing its absent value as 0
        would wipe every PR's numbers during the exact window where the detail
        call fails for all of them at once.
        """
        client = _CountingMockClient(tmp_path, [_listed_pr()])
        config = ProjectConfig(owner="apache", repo="spark")
        poll_project(client, config, operator_username="holdenk")
        assert PullRequest.objects.get(number=99).additions == 31

        def boom(owner: str, repo: str, pr_number: int) -> dict[str, Any]:
            msg = "403 rate limited"
            raise RuntimeError(msg)

        client.get_pull_request = boom  # type: ignore[method-assign]
        client.pr_list = [_listed_pr(updated_at="2026-04-09T11:00:00Z")]
        poll_project(client, config, operator_username="holdenk")

        pr = PullRequest.objects.get(number=99)
        assert (pr.additions, pr.deletions) == (31, 7)

    def test_operator_prs_refresh_more_often(self, tmp_path: Path) -> None:
        """mergeable only moves via the detail call, and shepherding reads it.

        The base branch advancing makes a PR conflicted without touching
        anything the listing can see, so the operator's own PRs can't wait out
        the full poll_refresh_hours window.
        """
        client = _CountingMockClient(tmp_path, [_listed_pr()])
        config = ProjectConfig(owner="apache", repo="spark", poll_refresh_hours=24)
        poll_project(client, config, operator_username="test-user")

        pr = PullRequest.objects.get(number=99)
        assert pr.is_operator_pr is True, "fixture author should be the operator"
        PullRequest.objects.filter(pk=pr.pk).update(
            last_polled_at=timezone.now() - timedelta(hours=2)
        )

        client.detail_calls.clear()
        assert len(poll_project(client, config, operator_username="test-user")) == 1
        assert client.detail_calls == [99]

    def test_third_party_prs_wait_for_the_full_window(self, tmp_path: Path) -> None:
        client = _CountingMockClient(tmp_path, [_listed_pr()])
        config = ProjectConfig(owner="apache", repo="spark", poll_refresh_hours=24)
        poll_project(client, config, operator_username="somebody-else")

        PullRequest.objects.filter(number=99).update(
            last_polled_at=timezone.now() - timedelta(hours=2)
        )
        client.detail_calls.clear()
        assert poll_project(client, config, operator_username="somebody-else") == []
        assert client.detail_calls == []

    def test_mention_scan_style_resave_does_not_reset_the_window(self, tmp_path: Path) -> None:
        """updated_at is auto_now, so any save bumps it.

        The mention scan re-ingests the operator's PRs every cycle via
        update_or_create; if the skip timer read updated_at, that would keep
        pushing the full-refresh deadline out of reach forever.
        """
        client = _CountingMockClient(tmp_path, [_listed_pr()])
        config = ProjectConfig(owner="apache", repo="spark", poll_refresh_hours=24)
        poll_project(client, config, operator_username="somebody-else")

        PullRequest.objects.filter(number=99).update(
            last_polled_at=timezone.now() - timedelta(days=2)
        )
        # Stand in for the mention scan's idempotent re-ingest.
        pr = PullRequest.objects.get(number=99)
        pr.save()
        assert pr.updated_at > pr.last_polled_at

        client.detail_calls.clear()
        assert len(poll_project(client, config, operator_username="somebody-else")) == 1
        assert client.detail_calls == [99]

    def test_skipped_prs_are_reported_to_the_caller(self, tmp_path: Path) -> None:
        """The cycle needs them for shepherding and the review backfill."""
        client = _CountingMockClient(tmp_path, [_listed_pr()])
        config = ProjectConfig(owner="apache", repo="spark")
        poll_project(client, config, operator_username="holdenk")

        skipped: list[PullRequest] = []
        assert poll_project(client, config, "holdenk", skipped_prs=skipped) == []
        assert [pr.number for pr in skipped] == [99]


@pytest.mark.django_db
class TestClosedPRReaping:
    """PRs closed upstream have to drop off the dashboard queues."""

    def _poll(self, client: MockGitHubClient) -> list[PullRequest]:
        return poll_project(
            client, ProjectConfig(owner="apache", repo="spark"), operator_username="holdenk"
        )

    def test_pr_missing_from_listing_is_closed(self, tmp_path: Path) -> None:
        client = _CountingMockClient(tmp_path, [_listed_pr(99), _listed_pr(100)])
        self._poll(client)
        assert PullRequest.objects.filter(state="open").count() == 2

        client.pr_list = [_listed_pr(100)]
        self._poll(client)
        assert PullRequest.objects.get(number=99).state == "closed"
        assert PullRequest.objects.get(number=100).state == "open"

    def test_empty_listing_closes_nothing(self, tmp_path: Path) -> None:
        """An empty listing is indistinguishable from a failed one."""
        client = _CountingMockClient(tmp_path, [_listed_pr(99)])
        self._poll(client)

        client.pr_list = []
        self._poll(client)
        assert PullRequest.objects.get(number=99).state == "open"

    def test_scraped_listing_closes_nothing(self, tmp_path: Path) -> None:
        """The HTML-scrape fallback is partial; reaping against it would be wrong."""
        client = _CountingMockClient(tmp_path, [_listed_pr(99), _listed_pr(100)])
        self._poll(client)

        client.pr_list = [_listed_pr(100) | {"_scraped": True}]
        self._poll(client)
        assert PullRequest.objects.get(number=99).state == "open"

    def test_truncated_listing_closes_nothing(self, tmp_path: Path) -> None:
        """A listing at the pagination cap may be missing PRs it didn't reach.

        Calls the reap directly: ingesting a thousand PRs through poll_project
        just to prove a guard fires costs seconds per run.
        """
        from franktheunicorn.backends.poller import _close_missing_pull_requests

        client = _CountingMockClient(tmp_path, [_listed_pr(99)])
        self._poll(client)
        project = Project.objects.get(owner="apache", repo="spark")

        at_cap = [_listed_pr(n) for n in range(1000, 1000 + MAX_LISTED_PULL_REQUESTS)]
        assert _close_missing_pull_requests(project, at_cap, client) == 0
        assert PullRequest.objects.get(number=99).state == "open"

        # One under the cap is trusted, and does reap.
        assert _close_missing_pull_requests(project, at_cap[:-1], client) == 1
        assert PullRequest.objects.get(number=99).state == "closed"

    def test_other_projects_are_untouched(self, tmp_path: Path) -> None:
        other = ProjectFactory(owner="holdenk", repo="spark")
        PullRequest.objects.create(
            project=other, github_id=1, number=7, title="theirs", author="holdenk", state="open"
        )
        client = _CountingMockClient(tmp_path, [_listed_pr(99)])
        self._poll(client)

        client.pr_list = [_listed_pr(100)]
        self._poll(client)
        assert PullRequest.objects.get(project=other, number=7).state == "open"


@pytest.mark.django_db
class TestReapRequiresCompleteListing:
    """Absence from a listing only means "closed" if the listing was complete."""

    def test_client_that_does_not_paginate_never_reaps(self, tmp_path: Path) -> None:
        """Gitea caps at 50 and GitLab at 50, neither paginating.

        Reaping against one short page would close every PR on the pages we
        never asked for.
        """

        class _ShortPageClient(_CountingMockClient):
            lists_all_open_pull_requests = False

        client = _ShortPageClient(tmp_path, [_listed_pr(99), _listed_pr(100)])
        config = ProjectConfig(owner="apache", repo="spark")
        poll_project(client, config, operator_username="holdenk")
        assert PullRequest.objects.filter(state="open").count() == 2

        # Second page's worth of PRs drops out of the (still truncated) listing.
        client.pr_list = [_listed_pr(100)]
        poll_project(client, config, operator_username="holdenk")

        assert PullRequest.objects.get(number=99).state == "open"

    def test_forge_clients_declare_their_listing_completeness(self) -> None:
        from franktheunicorn.backends.gitea import GiteaClient
        from franktheunicorn.backends.github import GitHubClient
        from franktheunicorn.backends.gitlab import GitLabClient

        assert GitHubClient.lists_all_open_pull_requests is True
        # These stop at one page today; flipping the flag requires pagination.
        assert GiteaClient.lists_all_open_pull_requests is False
        assert GitLabClient.lists_all_open_pull_requests is False
