"""Tests for session link detection (v1.25)."""

from __future__ import annotations

from franktheunicorn.core.session_detector import SessionInfo, detect_agent_session


class TestDetectAgentSession:
    def test_claude_code_session_link(self) -> None:
        body = "Generated by Claude Code\nSession: https://claude.ai/code/session/abc123\n"
        result = detect_agent_session(body)
        assert result == SessionInfo(
            agent_source="claude-code",
            session_url="https://claude.ai/code/session/abc123",
            task_id="",
        )

    def test_claude_code_inline_format(self) -> None:
        body = "This was created with claude-code session: https://claude.ai/code/session/xyz"
        result = detect_agent_session(body)
        assert result is not None
        assert result.agent_source == "claude-code"
        assert result.session_url == "https://claude.ai/code/session/xyz"

    def test_claude_code_case_insensitive(self) -> None:
        body = "session: https://claude.ai/code/session/ABC123"
        result = detect_agent_session(body)
        assert result is not None
        assert result.agent_source == "claude-code"

    def test_codex_task_id(self) -> None:
        body = "Generated by Codex\nTask ID: task_xyz789\n"
        result = detect_agent_session(body)
        assert result == SessionInfo(
            agent_source="codex",
            session_url="",
            task_id="task_xyz789",
        )

    def test_codex_inline_format(self) -> None:
        body = "codex task: task_abc123"
        result = detect_agent_session(body)
        assert result is not None
        assert result.agent_source == "codex"
        assert result.task_id == "task_abc123"

    def test_generic_generated_by_block(self) -> None:
        body = "Generated by SomeAgent\nhttps://someagent.example.com/session/123\n"
        result = detect_agent_session(body)
        assert result is not None
        assert result.agent_source == "generic"
        assert result.session_url == "https://someagent.example.com/session/123"

    def test_claude_code_rejects_non_url_session(self) -> None:
        body = "claude-code session: not-a-url"
        result = detect_agent_session(body)
        # Should not match — second pattern now requires https://
        assert result is None

    def test_no_match(self) -> None:
        body = "This PR fixes a bug in the scheduler module."
        result = detect_agent_session(body)
        assert result is None

    def test_empty_body(self) -> None:
        assert detect_agent_session("") is None

    def test_none_body(self) -> None:
        assert detect_agent_session(None) is None

    def test_first_match_wins(self) -> None:
        body = "Session: https://claude.ai/code/session/abc123\nTask ID: task_xyz789\n"
        result = detect_agent_session(body)
        assert result is not None
        assert result.agent_source == "claude-code"

    def test_session_url_stops_at_whitespace(self) -> None:
        body = "Session: https://claude.ai/code/session/abc123 and more text"
        result = detect_agent_session(body)
        assert result is not None
        assert result.session_url == "https://claude.ai/code/session/abc123"

    def test_task_id_stops_at_whitespace(self) -> None:
        body = "Task ID: task_xyz789 more text"
        result = detect_agent_session(body)
        assert result is not None
        assert result.task_id == "task_xyz789"
