"""Tests for the poller service."""

from __future__ import annotations

from typing import Any

import pytest

from franktheunicorn.config.models import ProjectConfig
from franktheunicorn.core.models import Project, PullRequest
from franktheunicorn.github.mock import MockGitHubClient
from franktheunicorn.github.poller import _upsert_pull_request, poll_project
from tests.factories import ProjectFactory


@pytest.mark.django_db
class TestPoller:
    def test_poll_creates_project_and_prs(self, tmp_path: Any) -> None:
        client = MockGitHubClient(tmp_path)
        config = ProjectConfig(
            owner="apache",
            repo="spark",
            watched_paths=["sql/catalyst/"],
            frequent_contributors=["cloud-fan"],
        )
        prs = poll_project(client, config, operator_username="holdenk")
        assert len(prs) == 3
        assert Project.objects.filter(owner="apache", repo="spark").exists()
        assert PullRequest.objects.count() == 3

    def test_poll_updates_existing_prs(self, tmp_path: Any) -> None:
        """Polling twice should update, not duplicate."""
        client = MockGitHubClient(tmp_path)
        config = ProjectConfig(owner="apache", repo="spark")
        poll_project(client, config, operator_username="holdenk")
        poll_project(client, config, operator_username="holdenk")
        assert PullRequest.objects.count() == 3

    def test_poll_scores_prs(self, tmp_path: Any) -> None:
        client = MockGitHubClient(tmp_path)
        config = ProjectConfig(
            owner="apache",
            repo="spark",
            watched_paths=["sql/"],
        )
        prs = poll_project(client, config, operator_username="holdenk")
        # PR #42 has holdenk as requested reviewer, so should score > 0
        pr42 = next(p for p in prs if p.number == 42)
        assert pr42.interest_score > 0
        assert len(pr42.score_breakdown) > 0


@pytest.mark.django_db
class TestSessionDetectionInPoller:
    """Tests for v1.25 session link detection during PR ingestion."""

    def test_claude_code_session_detected(self) -> None:
        project = ProjectFactory(owner="test", repo="repo")
        pr_data = {
            "number": 1,
            "id": 2001,
            "title": "AI-generated fix",
            "user": {"login": "claude-bot"},
            "state": "open",
            "html_url": "https://github.com/test/repo/pull/1",
            "diff_url": "",
            "body": ("Generated by Claude Code\nSession: https://claude.ai/code/session/abc123\n"),
            "labels": [],
            "requested_reviewers": [],
            "assignees": [],
            "draft": False,
            "additions": 10,
            "deletions": 2,
            "created_at": "2026-03-30T10:00:00Z",
            "updated_at": "2026-03-30T10:00:00Z",
        }
        pr = _upsert_pull_request(project, pr_data, ["src/fix.py"])
        assert pr.ai_agent_source == "claude-code"
        assert pr.agent_session_url == "https://claude.ai/code/session/abc123"
        assert pr.agent_task_id == ""
        assert pr.likely_ai_generated is True

    def test_codex_task_detected(self) -> None:
        project = ProjectFactory(owner="test", repo="repo")
        pr_data = {
            "number": 2,
            "id": 2002,
            "title": "Codex fix",
            "user": {"login": "codex-bot"},
            "state": "open",
            "html_url": "https://github.com/test/repo/pull/2",
            "diff_url": "",
            "body": "Generated by Codex\nTask ID: task_xyz789\n",
            "labels": [],
            "requested_reviewers": [],
            "assignees": [],
            "draft": False,
            "additions": 5,
            "deletions": 1,
            "created_at": "2026-03-30T10:00:00Z",
            "updated_at": "2026-03-30T10:00:00Z",
        }
        pr = _upsert_pull_request(project, pr_data, [])
        assert pr.ai_agent_source == "codex"
        assert pr.agent_task_id == "task_xyz789"
        assert pr.likely_ai_generated is True

    def test_no_session_leaves_fields_empty(self) -> None:
        project = ProjectFactory(owner="test", repo="repo")
        pr_data = {
            "number": 3,
            "id": 2003,
            "title": "Normal PR",
            "user": {"login": "human-dev"},
            "state": "open",
            "html_url": "https://github.com/test/repo/pull/3",
            "diff_url": "",
            "body": "Just a normal PR fixing a bug.",
            "labels": [],
            "requested_reviewers": [],
            "assignees": [],
            "draft": False,
            "additions": 10,
            "deletions": 5,
            "created_at": "2026-03-30T10:00:00Z",
            "updated_at": "2026-03-30T10:00:00Z",
        }
        pr = _upsert_pull_request(project, pr_data, [])
        assert pr.ai_agent_source == ""
        assert pr.agent_session_url == ""
        assert pr.agent_task_id == ""

    def test_stale_session_fields_cleared_on_body_change(self) -> None:
        """If a PR body previously had a session link but now doesn't, fields are cleared."""
        project = ProjectFactory(owner="test", repo="repo")
        # First ingestion: has session link
        pr_data_with_session = {
            "number": 4,
            "id": 2004,
            "title": "AI PR",
            "user": {"login": "bot"},
            "state": "open",
            "html_url": "https://github.com/test/repo/pull/4",
            "diff_url": "",
            "body": "Session: https://claude.ai/code/session/abc123",
            "labels": [],
            "requested_reviewers": [],
            "assignees": [],
            "draft": False,
            "additions": 1,
            "deletions": 1,
            "created_at": "2026-03-30T10:00:00Z",
            "updated_at": "2026-03-30T10:00:00Z",
        }
        pr = _upsert_pull_request(project, pr_data_with_session, [])
        assert pr.ai_agent_source == "claude-code"
        assert pr.agent_session_url == "https://claude.ai/code/session/abc123"

        # Second ingestion: session link removed from body
        pr_data_without_session = {**pr_data_with_session, "body": "Updated PR description."}
        pr = _upsert_pull_request(project, pr_data_without_session, [])
        assert pr.ai_agent_source == ""
        assert pr.agent_session_url == ""
        assert pr.agent_task_id == ""
