# Generated by Django 5.2.12 on 2026-03-30 21:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner", models.CharField(max_length=255)),
                ("repo", models.CharField(max_length=255)),
                ("review_context", models.TextField(default="general open-source")),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["owner", "repo"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "repo"), name="unique_project_owner_repo"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AntiPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pattern_text", models.TextField()),
                ("description", models.TextField(blank=True, default="")),
                (
                    "weight",
                    models.FloatField(
                        default=1.0,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("times_triggered", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anti_patterns",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-weight", "-times_triggered"],
            },
        ),
        migrations.CreateModel(
            name="PullRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github_id", models.IntegerField()),
                ("number", models.IntegerField()),
                ("title", models.CharField(max_length=1000)),
                ("author", models.CharField(max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("merged", "Merged"),
                        ],
                        default="open",
                        max_length=50,
                    ),
                ),
                ("url", models.URLField(max_length=1000)),
                ("diff_url", models.URLField(blank=True, default="", max_length=1000)),
                ("body", models.TextField(blank=True, default="")),
                ("labels", models.JSONField(blank=True, default=list)),
                ("requested_reviewers", models.JSONField(blank=True, default=list)),
                ("assignees", models.JSONField(blank=True, default=list)),
                ("changed_files", models.JSONField(blank=True, default=list)),
                ("additions", models.IntegerField(default=0)),
                ("deletions", models.IntegerField(default=0)),
                ("interest_score", models.FloatField(default=0.0)),
                ("score_breakdown", models.JSONField(blank=True, default=dict)),
                ("is_draft", models.BooleanField(default=False)),
                ("likely_ai_generated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("github_created_at", models.DateTimeField(blank=True, null=True)),
                ("github_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pull_requests",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-interest_score", "-github_updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DependencyChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("package_name", models.CharField(max_length=255)),
                ("ecosystem", models.CharField(max_length=50)),
                (
                    "old_version",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "new_version",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("source_file", models.CharField(max_length=500)),
                (
                    "changelog_url",
                    models.URLField(blank=True, default="", max_length=1000),
                ),
                ("changelog_text", models.TextField(blank=True, default="")),
                (
                    "repository_url",
                    models.URLField(blank=True, default="", max_length=1000),
                ),
                ("breaking_changes_detected", models.BooleanField(default=False)),
                ("deprecations_detected", models.BooleanField(default=False)),
                (
                    "changelog_fetch_error",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "pull_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependency_changes",
                        to="core.pullrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["package_name"],
            },
        ),
        migrations.CreateModel(
            name="ReviewDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                ("line_number", models.IntegerField(blank=True, null=True)),
                ("comment_body", models.TextField()),
                ("suggestion", models.TextField(blank=True, default="")),
                (
                    "confidence",
                    models.FloatField(
                        default=0.5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("source", models.CharField(default="agent", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("edited", "Edited"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("edited_body", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pull_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_drafts",
                        to="core.pullrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OperatorAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("accept_draft", "Accept Draft"),
                            ("reject_draft", "Reject Draft"),
                            ("edit_draft", "Edit Draft"),
                            ("dismiss_pr", "Dismiss PR"),
                            ("flag_anti_pattern", "Flag Anti-Pattern"),
                        ],
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "pull_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="core.pullrequest",
                    ),
                ),
                (
                    "review_draft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="core.reviewdraft",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="pullrequest",
            constraint=models.UniqueConstraint(
                fields=("project", "number"), name="unique_pr_project_number"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dependencychange",
            unique_together={("pull_request", "package_name", "source_file")},
        ),
    ]
