# Generated by Django 5.2.12 on 2026-03-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewdraft",
            name="source",
            field=models.CharField(default="agent", max_length=50),
        ),
    ]
