# Generated by Django 5.2.12 on 2026-03-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pullrequest",
            name="assignees",
            field=models.JSONField(default=list),
        ),
    ]
