# Generated by Django 5.2.12 on 2026-03-30 21:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DependencyChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("package_name", models.CharField(max_length=255)),
                ("ecosystem", models.CharField(max_length=50)),
                (
                    "old_version",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "new_version",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("source_file", models.CharField(max_length=500)),
                (
                    "changelog_url",
                    models.URLField(blank=True, default="", max_length=1000),
                ),
                ("changelog_text", models.TextField(blank=True, default="")),
                (
                    "repository_url",
                    models.URLField(blank=True, default="", max_length=1000),
                ),
                ("breaking_changes_detected", models.BooleanField(default=False)),
                ("deprecations_detected", models.BooleanField(default=False)),
                (
                    "changelog_fetch_error",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "pull_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependency_changes",
                        to="core.pullrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["package_name"],
                "unique_together": {("pull_request", "package_name", "source_file")},
            },
        ),
    ]
