# Generated by Django 5.2.12 on 2026-03-31 00:03

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="antipattern",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="antipattern",
            name="last_matched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="is_likely_unowned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="is_low_context",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="is_new_contributor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="is_operator_pr",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="queue",
            field=models.CharField(
                choices=[
                    ("review", "Review"),
                    ("ai-generated", "AI-Generated"),
                    ("new-contributor", "New Contributor"),
                    ("consider-closing", "Consider Closing"),
                    ("needs-triage", "Needs Triage"),
                    ("your-prs", "Your PRs"),
                ],
                default="review",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="reviewdraft",
            name="backend_used",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="reviewdraft",
            name="category",
            field=models.CharField(
                choices=[
                    ("correctness", "Correctness"),
                    ("style", "Style"),
                    ("security", "Security"),
                    ("test-coverage", "Test Coverage"),
                    ("architectural", "Architectural"),
                    ("naming", "Naming"),
                    ("suggested-change", "Suggested Change"),
                    ("moderation", "Moderation"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="reviewdraft",
            name="github_comment_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewdraft",
            name="line_end",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewdraft",
            name="posted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewdraft",
            name="reasoning_trace",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="reviewdraft",
            name="rejection_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="reviewdraft",
            name="severity",
            field=models.CharField(
                choices=[
                    ("critical", "Critical"),
                    ("important", "Important"),
                    ("nit", "Nit"),
                    ("informational", "Informational"),
                ],
                default="nit",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="reviewdraft",
            name="tone_guard_applied",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="reviewdraft",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("edited", "Edited"),
                    ("rejected", "Rejected"),
                    ("posted", "Posted"),
                    ("recalled", "Recalled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CostRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_type", models.CharField(max_length=50)),
                ("backend", models.CharField(blank=True, default="", max_length=100)),
                ("tokens_in", models.IntegerField(default=0)),
                ("tokens_out", models.IntegerField(default=0)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=8
                    ),
                ),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_records",
                        to="core.project",
                    ),
                ),
                (
                    "pull_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cost_records",
                        to="core.pullrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("pr_branch", "PR Branch"),
                            ("base_cherry_pick", "Base + Cherry-Picked Tests"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("test_scope", models.JSONField(default=list)),
                ("results", models.JSONField(blank=True, null=True)),
                (
                    "differential_verdict",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("good", "Good"),
                            ("suspect", "Suspect"),
                            ("broken", "Broken"),
                            ("infra", "Infra"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "container_image",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("error_log", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "pull_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_runs",
                        to="core.pullrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
