# Generated by Django 5.2.12 on 2026-03-30 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_source_to_reviewdraft"),
        ("core", "0002_pullrequest_assignees"),
    ]

    operations = []
