# Generated by Django 5.2.12 on 2026-03-31 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_antipattern_is_active_antipattern_last_matched_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pullrequest",
            name="mergeable",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
