# Generated by Django 5.2.12 on 2026-03-31 06:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_pullrequest_mergeable"),
    ]

    operations = [
        migrations.AddField(
            model_name="pullrequest",
            name="agent_session_url",
            field=models.URLField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="agent_task_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="ai_agent_source",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.CreateModel(
            name="AgentFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assessment",
                    models.CharField(
                        choices=[
                            ("good", "Good"),
                            ("needs-work", "Needs Work"),
                            ("reject", "Reject"),
                        ],
                        max_length=20,
                    ),
                ),
                ("feedback_body", models.TextField()),
                (
                    "feedback_method",
                    models.CharField(
                        choices=[
                            ("session-url", "Session URL"),
                            ("github-comment", "GitHub Comment"),
                        ],
                        default="session-url",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "pull_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_feedbacks",
                        to="core.pullrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
