# Generated by Django 5.2.12 on 2026-03-31 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_agent_feedback_v125"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewdraft",
            name="code_context",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="reviewdraft",
            name="is_auto_suppressed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reviewdraft",
            name="rejection_probability",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
