# Generated by Django 5.2.12 on 2026-03-31 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_agent_feedback_v125"),
    ]

    operations = [
        migrations.AddField(
            model_name="pullrequest",
            name="community_context_cache",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="jira_cache",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="jira_ticket_id",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="sentry_context_cache",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
