# Generated by Django 5.2.12 on 2026-04-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_reviewdraft_code_context_and_more"),
        ("core", "0005_v15_context_fields"),
    ]

    operations = []
