# Generated by Django 5.2.12 on 2026-04-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_merge_20260401_1720"),
    ]

    operations = [
        migrations.AddField(
            model_name="pullrequest",
            name="approval_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="ci_status",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="last_shepherded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="merge_queue_eligible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="merged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="merged_by",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="reviewer_comment_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="operatoraction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("accept_draft", "Accept Draft"),
                    ("reject_draft", "Reject Draft"),
                    ("edit_draft", "Edit Draft"),
                    ("dismiss_pr", "Dismiss PR"),
                    ("flag_anti_pattern", "Flag Anti-Pattern"),
                    ("accept_shepherd", "Accept Shepherd Draft"),
                    ("reject_shepherd", "Reject Shepherd Draft"),
                    ("edit_shepherd", "Edit Shepherd Draft"),
                ],
                max_length=50,
            ),
        ),
    ]
