# Generated by Django 5.2.12 on 2026-04-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_v2_shepherding_merge_queue"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="config_yaml",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="project",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("asf", "ASF"),
                    ("personal", "Personal"),
                    ("org", "Organization"),
                ],
                default="personal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="has_test_coverage",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
