# Generated by Django 5.2.12 on 2026-04-02 00:45
from __future__ import annotations

from typing import Any

from django.db import migrations, models


def forwards(apps: Any, schema_editor: Any) -> None:
    ReviewDraft = apps.get_model("core", "ReviewDraft")
    for draft in ReviewDraft.objects.all():
        old_source = draft.source or "agent"
        # Handle comma-separated sources like "agent,coderabbit"
        draft.sources = [s.strip() for s in old_source.split(",") if s.strip()]
        draft.save(update_fields=["sources"])


def backwards(apps: Any, schema_editor: Any) -> None:
    ReviewDraft = apps.get_model("core", "ReviewDraft")
    for draft in ReviewDraft.objects.all():
        draft.source = ",".join(draft.sources) if draft.sources else "agent"
        draft.save(update_fields=["source"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_add_project_type_name_config_yaml_and_has_test_coverage"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewdraft",
            name="sources",
            field=models.JSONField(default=list),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name="reviewdraft",
            name="source",
        ),
    ]
