# Generated by Django 5.2.13 on 2026-04-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_reviewdraft_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="repo_health_analyzed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="repo_health_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
