# Generated by Django 5.2.13 on 2026-04-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_add_repo_health_to_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewdraft",
            name="category",
            field=models.CharField(
                choices=[
                    ("correctness", "Correctness"),
                    ("style", "Style"),
                    ("security", "Security"),
                    ("security-context", "Security Context"),
                    ("test-coverage", "Test Coverage"),
                    ("architectural", "Architectural"),
                    ("naming", "Naming"),
                    ("suggested-change", "Suggested Change"),
                    ("moderation", "Moderation"),
                    ("issue-link", "Issue Link"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
