# Generated by Django 5.2.13 on 2026-04-09 06:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_reviewdraft_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=500)),
                ("raw_text", models.TextField()),
                (
                    "source",
                    models.CharField(
                        choices=[("paste", "Pasted"), ("email", "Email")],
                        default="paste",
                        max_length=20,
                    ),
                ),
                (
                    "reporter_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "reporter_email",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("triaging", "Triaging"),
                            ("valid", "Valid"),
                            ("invalid", "Invalid"),
                            ("duplicate", "Duplicate"),
                            ("expected-behavior", "Expected Behavior"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "parsed_component",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("parsed_poc", models.TextField(blank=True, default="")),
                ("parsed_impact", models.TextField(blank=True, default="")),
                (
                    "assessed_severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("informational", "Informational"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("triage_summary", models.TextField(blank=True, default="")),
                ("is_expected_behavior", models.BooleanField(default=False)),
                (
                    "expected_behavior_explanation",
                    models.TextField(blank=True, default=""),
                ),
                ("poc_assessment", models.TextField(blank=True, default="")),
                ("poc_plausible", models.BooleanField(blank=True, null=True)),
                ("sandbox_requested", models.BooleanField(default=False)),
                ("sandbox_result", models.TextField(blank=True, default="")),
                (
                    "sandbox_verdict",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("cve_matches", models.JSONField(blank=True, default=list)),
                (
                    "matched_cve_id",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("operator_notes", models.TextField(blank=True, default="")),
                (
                    "email_message_id",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("email_received_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_reports",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
