# Generated by Django 5.2.13 on 2026-04-30 04:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_securityreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentVibe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("backend", models.CharField(max_length=100)),
                ("vibe_text", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pull_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_vibes",
                        to="core.pullrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["backend", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pull_request", "backend"),
                        name="uniq_agentvibe_pr_backend",
                    )
                ],
            },
        ),
    ]
