# Generated by Django 5.2.13 on 2026-04-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_securityreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMBackendFallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=200)),
                ('base_url', models.CharField(blank=True, default='', max_length=500)),
                ('token_param', models.CharField(default='max_completion_tokens', max_length=50)),
                ('supports_json_object', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['provider', 'model'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'model', 'base_url'), name='unique_llm_fallback_provider_model_base_url')],
            },
        ),
    ]
