# Generated by Django 5.2.14 on 2026-05-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_github_comment_id_to_forge_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributors_cache',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
