# Generated by Django 5.2.14 on 2026-05-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_contributors_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdraft',
            name='diff_source',
            field=models.CharField(blank=True, choices=[('github_api', 'GitHub API'), ('github_scrape', 'GitHub Scrape'), ('local_git_merged', 'Local Git (Merged)')], default='', max_length=25),
        ),
    ]
