# Generated by Django 5.2.15 on 2026-07-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_workercommand"),
    ]

    operations = [
        migrations.AddField(
            model_name="testrun",
            name="head_sha",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="pullrequest",
            name="github_id",
            field=models.BigIntegerField(),
        ),
    ]
