# Generated by Django 5.2.15 on 2026-07-02 21:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_testrun_head_sha_alter_pullrequest_github_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="pullrequest",
            name="head_branch",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.CreateModel(
            name="EmailScanRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scanned_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("folder", models.CharField(blank=True, default="", max_length=255)),
                (
                    "message_id",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=500)),
                ("from_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "from_email",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_forwarded", models.BooleanField(default=False)),
                ("matched_keywords", models.JSONField(blank=True, default=list)),
                ("classified_security", models.BooleanField(default=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ingested", "Ingested as security report"),
                            (
                                "skipped_not_security",
                                "Skipped — did not match security filter",
                            ),
                            ("skipped_duplicate", "Skipped — already ingested"),
                        ],
                        default="skipped_not_security",
                        max_length=32,
                    ),
                ),
                (
                    "security_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_records",
                        to="core.securityreport",
                    ),
                ),
            ],
            options={
                "ordering": ["-scanned_at"],
                "indexes": [
                    models.Index(
                        fields=["-scanned_at"], name="core_emails_scanned_1f49af_idx"
                    )
                ],
            },
        ),
    ]
