# Generated by Django 5.2.16 on 2026-07-09 23:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_pullrequest_head_branch_emailscanrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("working-overlap", "Working Overlap"),
                            ("security-report", "Security Report"),
                        ],
                        max_length=30,
                    ),
                ),
                ("dedup_key", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("reasons", models.JSONField(blank=True, default=list)),
                ("email_sent", models.BooleanField(default=False)),
                ("emailed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="core.project",
                    ),
                ),
                (
                    "pull_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="core.pullrequest",
                    ),
                ),
                (
                    "security_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="core.securityreport",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email_sent", "created_at"],
                        name="core_alert_email_s_40dd32_idx",
                    )
                ],
            },
        ),
    ]
