# Generated by Django 5.2.16 on 2026-07-11 06:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_reviewdraft_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costrecord",
            name="estimated_cost_usd",
            field=models.DecimalField(
                decimal_places=6, default=Decimal("0.000000"), max_digits=12
            ),
        ),
    ]
