# Generated by Codex on 2026-07-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_reviewdraft_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="contributors_cache_status",
            field=models.CharField(blank=True, default="unknown", max_length=20),
        ),
    ]
