# Generated by Django 5.2.16 on 2026-07-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_costrecord_estimated_cost_usd"),
    ]

    operations = [
        migrations.AddField(
            model_name="pullrequest",
            name="is_mentioned",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pullrequest",
            name="queue",
            field=models.CharField(
                choices=[
                    ("review", "Review"),
                    ("ai-generated", "AI-Generated"),
                    ("new-contributor", "New Contributor"),
                    ("consider-closing", "Consider Closing"),
                    ("needs-triage", "Needs Triage"),
                    ("your-prs", "Your PRs"),
                    ("mentioned", "Mentioned"),
                    ("wip", "WIP"),
                ],
                default="review",
                max_length=50,
            ),
        ),
    ]
