# Generated by Django 5.2.16 on 2026-07-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_securitytriagefeedback_securitytriageguidance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workercommand',
            name='command',
            field=models.CharField(choices=[('run_dual_tests', 'Run differential tests'), ('run_security_sandbox', 'Run security report sandbox'), ('run_security_triage', 'Run LLM triage on security report'), ('run_agents', 'Force-run review agents')], max_length=50),
        ),
    ]
