# Generated by Django 5.2.16 on 2026-08-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_add_run_security_triage_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='last_polled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
