# Generated by Django 5.2.16 on 2026-08-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_pullrequest_last_polled_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workercommand',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running'])), fields=('command', 'security_report'), name='unique_inflight_command_per_report'),
        ),
    ]
