# Generated by Django 5.2.16 on 2026-08-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_workercommand_inflight_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityreport',
            name='source',
            field=models.CharField(choices=[('paste', 'Pasted'), ('email', 'Email'), ('zip', 'Zip import')], default='paste', max_length=20),
        ),
    ]
