# Generated by Django 5.2.16 on 2026-08-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_securityreport_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityreport',
            name='source_archive',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
