# Generated by Django 5.2.16 on 2026-08-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_securityreport_source_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityreport',
            name='finding_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='proposed_patch',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='proposed_patch_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
