# Generated by Django 5.2.16 on 2026-08-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_securityreport_finding_and_patch'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityreport',
            name='priority',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='priority_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
