# Generated by Django 5.2.16 on 2026-08-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_securityreport_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workercommand',
            options={'ordering': ['-priority', 'created_at']},
        ),
        migrations.AddField(
            model_name='workercommand',
            name='priority',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='workercommand',
            index=models.Index(fields=['status', '-priority', 'created_at'], name='core_worker_status_948116_idx'),
        ),
        migrations.AddConstraint(
            model_name='workercommand',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running'])), fields=('command', 'pull_request'), name='unique_inflight_command_per_pr'),
        ),
    ]
