# Generated by Django 5.2.16 on 2026-08-26 18:52
#
# Hand-edited to add _collapse_duplicate_inflight before the AddConstraint.
# Django emits a bare CREATE UNIQUE INDEX for a partial UniqueConstraint, so on
# any install that already holds two in-flight commands of a kind for one PR the
# index build fails and `manage.py migrate` dies with
#
#     IntegrityError: UNIQUE constraint failed:
#       core_workercommand.command, core_workercommand.pull_request_id
#
# leaving no way forward but hand-written SQL. Those installs are exactly the ones
# the constraint exists for: before it, every click of "Force Run Agents" queued
# another row, so a PR someone clicked twice is the normal case, not a corner one.

from typing import Any

from django.db import migrations, models


def _collapse_duplicate_inflight(apps: Any, schema_editor: Any) -> None:
    """Keep the oldest in-flight command per (command, pull_request); fail the rest.

    Failed rather than deleted: the row is the only record that the operator asked
    for something, and a worker log that says "superseded" is worth more than a
    silently shorter table. Only PR-targeted rows need this — the equivalent
    constraint for security reports has been enforced since 0032, so those cannot
    have duplicates.
    """
    WorkerCommand = apps.get_model("core", "WorkerCommand")
    inflight = (
        WorkerCommand.objects.filter(
            status__in=["pending", "running"], pull_request__isnull=False
        )
        .order_by("command", "pull_request_id", "created_at", "pk")
        .values_list("pk", "command", "pull_request_id")
    )
    keep: set[tuple[str, int]] = set()
    superseded: list[int] = []
    for pk, command, pull_request_id in inflight:
        key = (command, pull_request_id)
        if key in keep:
            superseded.append(pk)
        else:
            keep.add(key)
    if superseded:
        WorkerCommand.objects.filter(pk__in=superseded).update(
            status="failed",
            error="Superseded: an earlier in-flight command of this kind already "
            "existed for this PR. Collapsed by migration 0037, which added the "
            "constraint that now prevents the duplicate.",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_securityreport_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workercommand',
            options={'ordering': ['-priority', 'created_at']},
        ),
        migrations.AddField(
            model_name='workercommand',
            name='priority',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='workercommand',
            index=models.Index(fields=['status', '-priority', 'created_at'], name='core_worker_status_948116_idx'),
        ),
        # Before the constraint, or the index build hits the rows it forbids.
        migrations.RunPython(
            _collapse_duplicate_inflight,
            # Nothing to undo: the reverse of the constraint is dropping it, and
            # resurrecting superseded duplicates would recreate the bug.
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='workercommand',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running'])), fields=('command', 'pull_request'), name='unique_inflight_command_per_pr'),
        ),
    ]
