# Generated by Django 5.2.16 on 2026-08-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_workercommand_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='agent_runs',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
