# Generated by Django 5.2.16 on 2026-08-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_pullrequest_agent_runs'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityreport',
            name='external_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='external_notes_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
