# Generated by Django 5.2.16 on 2026-08-28 00:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_securityreport_external_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=255)),
                ('commit', models.CharField(blank=True, default='', max_length=64)),
                ('verdict', models.CharField(choices=[('affected', 'Affected'), ('not-affected', 'Not affected'), ('unclear', 'Unclear'), ('error', 'Could not check')], default='unclear', max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('evidence', models.TextField(blank=True, default='')),
                ('agent', models.CharField(blank=True, default='', max_length=100)),
                ('raw_output', models.TextField(blank=True, default='')),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='core.securityreport')),
            ],
            options={
                'ordering': ['-created_at', 'branch'],
                'constraints': [models.UniqueConstraint(fields=('report', 'branch'), name='unique_verification_per_report_branch')],
            },
        ),
    ]
