# Generated by Django 5.2.16 on 2026-08-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_security_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityverification',
            name='branch_order',
            field=models.IntegerField(default=0),
        ),
    ]
