# Generated by Django 5.2.16 on 2026-08-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_verification_branch_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityverification',
            name='version_impact',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
