# Generated by Django 5.2.16 on 2026-08-28 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_securityverification_version_impact'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityreport',
            name='duplicate_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='core.securityreport'),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='duplicate_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
