# Generated by Django 5.2.16 on 2026-08-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_securityreport_duplicate_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityreport',
            name='introduced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='introduced_commit',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='introduced_method',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='introduced_release_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='introduced_releases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='introduced_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
