# Generated by Django 5.2.16 on 2026-08-31 22:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_securityreport_auto_triage_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityreport',
            name='depends_on',
            field=models.ManyToManyField(blank=True, related_name='required_by', to='core.securityreport'),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='fix_agent_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='fix_base_branch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='fix_branch',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='fix_launched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='fix_run_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='fix_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='fix_status_detail',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='recheck_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='recheck_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='rechecked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workercommand',
            name='command',
            field=models.CharField(choices=[('run_dual_tests', 'Run differential tests'), ('run_security_sandbox', 'Run security report sandbox'), ('poll_security_rechecks', 'Wait on batch security rechecks'), ('run_security_triage', 'Run LLM triage on security report'), ('run_agents', 'Force-run review agents')], max_length=50),
        ),
        migrations.CreateModel(
            name='SecurityRecheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(blank=True, default='', max_length=100)),
                ('run_id', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('launched', 'Launched'), ('finished', 'Finished'), ('error', 'Error')], default='launched', max_length=20)),
                ('report_count', models.IntegerField(default=0)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_recheck_runs', to='core.project')),
            ],
        ),
    ]
