# Generated by Django 5.2.16 on 2026-09-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_securityreport_depends_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityrecheckrun',
            name='chunk_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='fix_branch_sha',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='fix_injection_hits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='fix_superseded',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddConstraint(
            model_name='securityrecheckrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'launched')), fields=('project', 'chunk_index'), name='unique_launched_recheck_per_project_chunk'),
        ),
    ]
