# Generated by Django 5.2.16 on 2026-09-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_fix_branch_provenance_and_recheck_dedup"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityreport",
            name="fixed_in_branch",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
