# Generated by Django 5.2.16 on 2026-09-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_securityreport_fixed_in_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityreport',
            name='fixed_in_branch',
            field=models.TextField(blank=True, default=''),
        ),
    ]
