# Generated by Django 5.2.16 on 2026-09-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_securityreport_fixed_in_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityreport',
            name='branch_match_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='branch_match_branch',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='branch_match_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='branch_match_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='branch_matched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='recheck_method',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
