# Generated by Django 5.2.16 on 2026-09-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_backfill_recheck_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityreport',
            name='recheck_method',
            field=models.CharField(blank=True, choices=[('', 'Never checked'), ('agent', 'Cloud agent read the commit log'), ('git', 'Reverse-applied the proposed patch')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='securityreport',
            name='recheck_status',
            field=models.CharField(blank=True, choices=[('', 'Never checked'), ('still-valid', 'Still valid'), ('likely-fixed', 'Likely fixed already'), ('unclear', 'The code moved — unclear')], default='', max_length=20),
        ),
    ]
