# Generated by Django 5.2.17 on 2026-09-24 23:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_security_fix_branch_columns_and_undo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVEAPIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmc', models.CharField(max_length=100)),
                ('op', models.CharField(choices=[('allocate', 'Allocate CVE ids'), ('write', 'Read and update CVE records')], max_length=20)),
                ('token', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['pmc', 'op'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='securityrecheckrun',
            name='unique_launched_recheck_per_project_chunk',
        ),
        migrations.AddField(
            model_name='securityrecheckrun',
            name='kind',
            field=models.CharField(choices=[('recheck', 'Did recent commits fix these?'), ('fix-landed', 'Did the known fix land upstream?')], default='recheck', max_length=20),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='cve_record_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='cve_record_state',
            field=models.CharField(blank=True, choices=[('', 'Never checked'), ('RESERVED', 'Reserved'), ('PUBLISHED', 'Published'), ('REJECT', 'Rejected'), ('unknown', 'Unrecognised response')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='fix_landed_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='fix_landed_detail',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='fix_landed_method',
            field=models.CharField(blank=True, choices=[('', 'Never checked'), ('git', 'Git ancestry and tag checks'), ('agent', 'Cloud agent read the commit log')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='fix_landed_status',
            field=models.CharField(blank=True, choices=[('', 'Never checked'), ('merged', 'Merged upstream'), ('released', 'In a release tag'), ('not-merged', 'Not merged upstream'), ('no-fix-branch', 'No fix branch to check'), ('indeterminate', 'Git could not prove it either way')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='workercommand',
            name='command',
            field=models.CharField(choices=[('run_dual_tests', 'Run differential tests'), ('run_security_sandbox', 'Run security report sandbox'), ('poll_security_rechecks', 'Wait on batch security rechecks'), ('run_security_triage', 'Run LLM triage on security report'), ('run_agents', 'Force-run review agents'), ('check_fix_landed', "Check whether one report's fix landed upstream"), ('check_fixes_landed', 'Sweep: check whether known fixes landed upstream')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='securityrecheckrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'launched')), fields=('project', 'kind', 'chunk_index'), name='unique_launched_recheck_per_project_chunk'),
        ),
        migrations.AddConstraint(
            model_name='cveapitoken',
            constraint=models.UniqueConstraint(fields=('pmc', 'op'), name='unique_cve_api_token_per_pmc_op'),
        ),
    ]
