# Generated by Django 5.2.17 on 2026-09-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_cve_api_and_fix_landed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityrecheckrun',
            name='kind',
            field=models.CharField(choices=[('recheck', 'Did recent commits fix these?'), ('fix-landed', 'Did the known fix land upstream?'), ('valid-check', 'Is this valid report fixed yet?')], default='recheck', max_length=20),
        ),
    ]
