"""Container image resolution + auto-build for the differential test runner.

Resolves the image to use for a given project's ``TestExecutionConfig`` in
priority order:

1. ``container_image`` — use as-is, no build.
2. ``dockerfile`` — build the named Dockerfile inside the repo.
3. ``auto_build`` — generate a Dockerfile from base image + requirements +
   setup commands, then build it.
4. None of the above — fall back to ``python:3.12-slim``.

Built images are tagged ``franktheunicorn-test/<owner>-<repo>:<hash>`` where
``<hash>`` is the sha256 of the Dockerfile bytes plus any referenced
requirements files. Subsequent runs with the same hash skip the build.
"""

from __future__ import annotations

import hashlib
import logging
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from franktheunicorn.config.models import TestAutoBuildConfig, TestExecutionConfig

logger = logging.getLogger(__name__)

DEFAULT_IMAGE = "python:3.12-slim"
IMAGE_TAG_PREFIX = "franktheunicorn-test"


def _hash_inputs(*chunks: bytes) -> str:
    h = hashlib.sha256()
    for c in chunks:
        h.update(c)
        h.update(b"\0")
    return h.hexdigest()[:12]


def _image_exists(docker: Any, tag: str) -> bool:
    try:
        docker.images.get(tag)
        return True
    except Exception:
        return False


def _read_optional(path: Path) -> bytes:
    try:
        return path.read_bytes()
    except OSError:
        return b""


def generate_auto_build_dockerfile(
    auto_build: TestAutoBuildConfig,
    workdir: str,
) -> str:
    """Render a Dockerfile from ``auto_build`` config (matches §9.6)."""
    lines: list[str] = [
        "# Auto-generated by franktheunicorn — do not edit",
        f"FROM {auto_build.base_image}",
        f"WORKDIR {workdir}",
    ]
    if auto_build.requirements_files:
        lines.append("COPY " + " ".join(auto_build.requirements_files) + f" {workdir}/")
        pip_args = " ".join(f"-r {f}" for f in auto_build.requirements_files)
        lines.append(f"RUN pip install --no-cache-dir {pip_args}")
    for cmd in auto_build.setup_commands:
        lines.append(f"RUN {cmd}")
    return "\n".join(lines) + "\n"


def resolve_image(
    docker: Any,
    owner: str,
    repo: str,
    tests: TestExecutionConfig,
    workspace: Path,
) -> str:
    """Return the image tag to run, building it if needed.

    ``workspace`` is the checked-out PR worktree; build context comes from
    there so relative paths (Dockerfile, requirements files) resolve
    correctly.
    """
    if tests.container_image:
        return tests.container_image

    if tests.dockerfile:
        df_path = workspace / tests.dockerfile
        if not df_path.is_file():
            msg = f"tests.dockerfile {tests.dockerfile!r} not found in repo workspace"
            raise FileNotFoundError(msg)
        df_bytes = df_path.read_bytes()
        tag = f"{IMAGE_TAG_PREFIX}/{owner}-{repo}:{_hash_inputs(df_bytes)}"
        if _image_exists(docker, tag):
            return tag
        logger.info("Building test image %s from %s", tag, tests.dockerfile)
        docker.images.build(
            path=str(workspace),
            dockerfile=tests.dockerfile,
            tag=tag,
            rm=True,
            pull=False,
        )
        return tag

    if tests.auto_build:
        df_text = generate_auto_build_dockerfile(tests.auto_build, tests.workdir)
        req_chunks = [_read_optional(workspace / f) for f in tests.auto_build.requirements_files]
        tag = (
            f"{IMAGE_TAG_PREFIX}/{owner}-{repo}:"
            f"{_hash_inputs(df_text.encode('utf-8'), *req_chunks)}"
        )
        if _image_exists(docker, tag):
            return tag
        logger.info("Building auto-build test image %s", tag)
        # Write the generated Dockerfile into the workspace so the build
        # context (requirements files, source code) is available.
        with tempfile.NamedTemporaryFile(
            mode="w",
            dir=str(workspace),
            prefix=".frank-autobuild-",
            suffix=".Dockerfile",
            delete=False,
        ) as fh:
            fh.write(df_text)
            df_name = Path(fh.name).name
        try:
            docker.images.build(
                path=str(workspace),
                dockerfile=df_name,
                tag=tag,
                rm=True,
                pull=False,
            )
        finally:
            (workspace / df_name).unlink(missing_ok=True)
        return tag

    return DEFAULT_IMAGE
