#!/usr/bin/env bash
# Launch franktheunicorn with all configured local inference services.
#
# Automatically detects compose override files generated by setup_llm
# (compose.ollama.yaml, compose.llama-cpp.yaml, compose.vllm.yaml)
# and includes them in the docker compose command.
#
# Usage:
#   ./scripts/launch.sh              # foreground
#   ./scripts/launch.sh -d           # detached
#   ./scripts/launch.sh --build      # rebuild images first
#   ./scripts/launch.sh logs -f      # tail logs (any compose subcommand)

set -euo pipefail

cd "$(dirname "$0")/.."

COMPOSE_FILES=("-f" "compose.yaml")

# Auto-detect generated compose overrides for local inference
for override in compose.ollama.yaml compose.llama-cpp.yaml compose.vllm.yaml; do
    if [ -f "$override" ]; then
        COMPOSE_FILES+=("-f" "$override")
    fi
done

echo "Compose files: ${COMPOSE_FILES[*]}"

# Default to "up" if no subcommand given
if [ $# -eq 0 ]; then
    exec docker compose "${COMPOSE_FILES[@]}" up
else
    exec docker compose "${COMPOSE_FILES[@]}" "$@"
fi
