"""
Django models for franktheunicorn.

Local-first: all data lives in SQLite. No multi-tenancy, no user accounts.
These models track ingested PRs, draft reviews, anti-patterns, and operator actions.
"""

from __future__ import annotations

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils import timezone


class Project(models.Model):
    """A GitHub repository the operator is monitoring."""

    owner = models.CharField(max_length=255)
    repo = models.CharField(max_length=255)
    review_context = models.TextField(default="general open-source")
    enabled = models.BooleanField(default=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["owner", "repo"], name="unique_project_owner_repo"),
        ]
        ordering = ["owner", "repo"]

    def __str__(self) -> str:
        return self.full_name

    @property
    def full_name(self) -> str:
        return f"{self.owner}/{self.repo}"


class PullRequest(models.Model):
    """A pull request ingested from GitHub."""

    STATE_CHOICES = [
        ("open", "Open"),
        ("closed", "Closed"),
        ("merged", "Merged"),
    ]

    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="pull_requests")
    github_id = models.IntegerField()
    number = models.IntegerField()
    title = models.CharField(max_length=1000)
    author = models.CharField(max_length=255)
    state = models.CharField(max_length=50, choices=STATE_CHOICES, default="open")
    url = models.URLField(max_length=1000)
    diff_url = models.URLField(max_length=1000, blank=True, default="")
    body = models.TextField(blank=True, default="")
    labels = models.JSONField(default=list, blank=True)
    requested_reviewers = models.JSONField(default=list, blank=True)
    changed_files = models.JSONField(default=list, blank=True)
    additions = models.IntegerField(default=0)
    deletions = models.IntegerField(default=0)

    # Scoring
    interest_score = models.FloatField(default=0.0)
    score_breakdown = models.JSONField(default=dict, blank=True)

    # Flags
    is_draft = models.BooleanField(default=False)
    likely_ai_generated = models.BooleanField(default=False)

    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    github_created_at = models.DateTimeField(null=True, blank=True)
    github_updated_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["project", "number"], name="unique_pr_project_number"
            ),
        ]
        ordering = ["-interest_score", "-github_updated_at"]

    def __str__(self) -> str:
        return f"#{self.number} {self.title}"


class ReviewDraft(models.Model):
    """A draft review comment generated by the LLM (or stub)."""

    pull_request = models.ForeignKey(
        PullRequest, on_delete=models.CASCADE, related_name="review_drafts"
    )
    file_path = models.CharField(max_length=1000, blank=True, default="")
    line_number = models.IntegerField(null=True, blank=True)
    comment_body = models.TextField()
    suggestion = models.TextField(blank=True, default="")
    confidence = models.FloatField(
        default=0.5, validators=[MinValueValidator(0.0), MaxValueValidator(1.0)]
    )

    # Operator disposition
    STATUS_CHOICES = [
        ("pending", "Pending"),
        ("accepted", "Accepted"),
        ("edited", "Edited"),
        ("rejected", "Rejected"),
    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="pending")
    edited_body = models.TextField(blank=True, default="")

    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return f"Draft for {self.pull_request} @ {self.file_path}:{self.line_number}"


class AntiPattern(models.Model):
    """
    A pattern of review comment the operator doesn't want to make.

    Built from rejected/edited drafts. Used as a lightweight feedback signal
    to reduce pedantic or abrasive suggestions over time.
    """

    pattern_text = models.TextField()
    description = models.TextField(blank=True, default="")
    weight = models.FloatField(default=1.0, validators=[MinValueValidator(0.0)])
    times_triggered = models.IntegerField(default=0)
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, related_name="anti_patterns", null=True, blank=True
    )
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-weight", "-times_triggered"]

    def __str__(self) -> str:
        return f"AntiPattern: {self.pattern_text[:60]}"


class OperatorAction(models.Model):
    """
    Log of operator actions (accept/reject/edit a draft, dismiss a PR, etc.).

    Primary feedback loop for learning what the operator values.
    """

    ACTION_CHOICES = [
        ("accept_draft", "Accept Draft"),
        ("reject_draft", "Reject Draft"),
        ("edit_draft", "Edit Draft"),
        ("dismiss_pr", "Dismiss PR"),
        ("flag_anti_pattern", "Flag Anti-Pattern"),
    ]
    action_type = models.CharField(max_length=50, choices=ACTION_CHOICES)
    review_draft = models.ForeignKey(
        ReviewDraft, on_delete=models.SET_NULL, null=True, blank=True, related_name="actions"
    )
    pull_request = models.ForeignKey(
        PullRequest, on_delete=models.SET_NULL, null=True, blank=True, related_name="actions"
    )
    notes = models.TextField(blank=True, default="")
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return f"{self.action_type} at {self.created_at}"
