"""
Django models for franktheunicorn.

Local-first: all data lives in SQLite. No multi-tenancy, no user accounts.
These models track ingested PRs, draft reviews, anti-patterns, and operator actions.
"""

from __future__ import annotations

from decimal import Decimal

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils import timezone


class Project(models.Model):
    """A GitHub repository the operator is monitoring."""

    owner = models.CharField(max_length=255)
    repo = models.CharField(max_length=255)
    review_context = models.TextField(default="general open-source")
    enabled = models.BooleanField(default=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["owner", "repo"], name="unique_project_owner_repo"),
        ]
        ordering = ["owner", "repo"]

    def __str__(self) -> str:
        return self.full_name

    @property
    def full_name(self) -> str:
        return f"{self.owner}/{self.repo}"


class PullRequest(models.Model):
    """A pull request ingested from GitHub."""

    STATE_CHOICES = [
        ("open", "Open"),
        ("closed", "Closed"),
        ("merged", "Merged"),
    ]

    QUEUE_CHOICES = [
        ("review", "Review"),
        ("ai-generated", "AI-Generated"),
        ("new-contributor", "New Contributor"),
        ("consider-closing", "Consider Closing"),
        ("needs-triage", "Needs Triage"),
        ("your-prs", "Your PRs"),
    ]

    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="pull_requests")
    github_id = models.IntegerField()
    number = models.IntegerField()
    title = models.CharField(max_length=1000)
    author = models.CharField(max_length=255)
    state = models.CharField(max_length=50, choices=STATE_CHOICES, default="open")
    url = models.URLField(max_length=1000)
    diff_url = models.URLField(max_length=1000, blank=True, default="")
    body = models.TextField(blank=True, default="")
    labels = models.JSONField(default=list, blank=True)
    requested_reviewers = models.JSONField(default=list, blank=True)
    assignees = models.JSONField(default=list, blank=True)
    changed_files = models.JSONField(default=list, blank=True)
    additions = models.IntegerField(default=0)
    deletions = models.IntegerField(default=0)

    # Scoring
    interest_score = models.FloatField(default=0.0)
    score_breakdown = models.JSONField(default=dict, blank=True)

    # Flags
    is_draft = models.BooleanField(default=False)
    likely_ai_generated = models.BooleanField(default=False)
    is_operator_pr = models.BooleanField(default=False)
    is_new_contributor = models.BooleanField(default=False)
    is_low_context = models.BooleanField(default=False)
    is_likely_unowned = models.BooleanField(default=False)

    # Agent session tracking (v1.25 — direct feedback channel)
    ai_agent_source = models.CharField(max_length=100, blank=True, default="")
    agent_session_url = models.URLField(max_length=1000, blank=True, default="")
    agent_task_id = models.CharField(max_length=255, blank=True, default="")

    # Merge status (fetched from single-PR endpoint)
    mergeable = models.BooleanField(null=True, blank=True)

    # Queue routing (§2.2)
    queue = models.CharField(max_length=50, choices=QUEUE_CHOICES, default="review")

    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    github_created_at = models.DateTimeField(null=True, blank=True)
    github_updated_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["project", "number"], name="unique_pr_project_number"),
        ]
        ordering = ["-interest_score", "-github_updated_at"]

    def __str__(self) -> str:
        return f"#{self.number} {self.title}"


class ReviewDraft(models.Model):
    """A draft review finding generated by the LLM (or stub).

    This is the persisted form of a ReviewFinding. The design doc calls
    the core abstraction 'ReviewFinding'; ReviewDraft is the Django model name.
    """

    CATEGORY_CHOICES = [
        ("correctness", "Correctness"),
        ("style", "Style"),
        ("security", "Security"),
        ("test-coverage", "Test Coverage"),
        ("architectural", "Architectural"),
        ("naming", "Naming"),
        ("suggested-change", "Suggested Change"),
        ("moderation", "Moderation"),
        ("other", "Other"),
    ]

    SEVERITY_CHOICES = [
        ("critical", "Critical"),
        ("important", "Important"),
        ("nit", "Nit"),
        ("informational", "Informational"),
    ]

    pull_request = models.ForeignKey(
        PullRequest, on_delete=models.CASCADE, related_name="review_drafts"
    )
    file_path = models.CharField(max_length=1000, blank=True, default="")
    line_number = models.IntegerField(null=True, blank=True)
    line_end = models.IntegerField(null=True, blank=True)
    comment_body = models.TextField()
    suggestion = models.TextField(blank=True, default="")
    confidence = models.FloatField(
        default=0.5, validators=[MinValueValidator(0.0), MaxValueValidator(1.0)]
    )
    source = models.CharField(max_length=50, default="agent")

    # Finding metadata (§3.2)
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES, default="other")
    severity = models.CharField(max_length=20, choices=SEVERITY_CHOICES, default="nit")
    reasoning_trace = models.TextField(blank=True, default="")
    tone_guard_applied = models.BooleanField(default=False)
    backend_used = models.CharField(max_length=100, blank=True, default="")

    # Operator disposition
    STATUS_CHOICES = [
        ("pending", "Pending"),
        ("accepted", "Accepted"),
        ("edited", "Edited"),
        ("rejected", "Rejected"),
        ("posted", "Posted"),
        ("recalled", "Recalled"),
    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="pending")
    edited_body = models.TextField(blank=True, default="")
    rejection_reason = models.TextField(blank=True, default="")

    # GitHub posting state
    github_comment_id = models.BigIntegerField(null=True, blank=True)
    posted_at = models.DateTimeField(null=True, blank=True)

    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return f"Draft for {self.pull_request} @ {self.file_path}:{self.line_number}"


class AntiPattern(models.Model):
    """
    A pattern of review comment the operator doesn't want to make.

    Built from rejected/edited drafts. Used as a lightweight feedback signal
    to reduce pedantic or abrasive suggestions over time.
    """

    pattern_text = models.TextField()
    description = models.TextField(blank=True, default="")
    weight = models.FloatField(default=1.0, validators=[MinValueValidator(0.0)])
    times_triggered = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, related_name="anti_patterns", null=True, blank=True
    )
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    last_matched_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ["-weight", "-times_triggered"]

    def __str__(self) -> str:
        return f"AntiPattern: {self.pattern_text[:60]}"


class DependencyChange(models.Model):
    """A dependency version change detected in a PR, with optional changelog data.

    Created when a PR modifies dependency files (requirements.txt, pyproject.toml, etc.).
    Changelog data is fetched from PyPI + GitHub and stored for review context.
    """

    pull_request = models.ForeignKey(
        PullRequest, on_delete=models.CASCADE, related_name="dependency_changes"
    )
    package_name = models.CharField(max_length=255)
    ecosystem = models.CharField(max_length=50)  # "python", "java", "rust"
    old_version = models.CharField(max_length=100, blank=True, default="")
    new_version = models.CharField(max_length=100, blank=True, default="")
    source_file = models.CharField(max_length=500)
    changelog_url = models.URLField(max_length=1000, blank=True, default="")
    changelog_text = models.TextField(blank=True, default="")
    repository_url = models.URLField(max_length=1000, blank=True, default="")
    breaking_changes_detected = models.BooleanField(default=False)
    deprecations_detected = models.BooleanField(default=False)
    changelog_fetch_error = models.CharField(max_length=500, blank=True, default="")
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        unique_together = [("pull_request", "package_name", "source_file")]
        ordering = ["package_name"]

    def __str__(self) -> str:
        old = self.old_version or "new"
        new = self.new_version or "removed"
        return f"{self.package_name}: {old} → {new}"


class OperatorAction(models.Model):
    """
    Log of operator actions (accept/reject/edit a draft, dismiss a PR, etc.).

    Primary feedback loop for learning what the operator values.
    """

    ACTION_CHOICES = [
        ("accept_draft", "Accept Draft"),
        ("reject_draft", "Reject Draft"),
        ("edit_draft", "Edit Draft"),
        ("dismiss_pr", "Dismiss PR"),
        ("flag_anti_pattern", "Flag Anti-Pattern"),
    ]
    action_type = models.CharField(max_length=50, choices=ACTION_CHOICES)
    review_draft = models.ForeignKey(
        ReviewDraft, on_delete=models.SET_NULL, null=True, blank=True, related_name="actions"
    )
    pull_request = models.ForeignKey(
        PullRequest, on_delete=models.SET_NULL, null=True, blank=True, related_name="actions"
    )
    notes = models.TextField(blank=True, default="")
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return f"{self.action_type} at {self.created_at}"


class CostRecord(models.Model):
    """Tracks LLM API token usage and estimated cost per call."""

    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="cost_records")
    pull_request = models.ForeignKey(
        PullRequest, on_delete=models.SET_NULL, null=True, blank=True, related_name="cost_records"
    )
    action_type = models.CharField(max_length=50)  # "review", "tone-guard", "scoring"
    backend = models.CharField(max_length=100, blank=True, default="")
    tokens_in = models.IntegerField(default=0)
    tokens_out = models.IntegerField(default=0)
    estimated_cost_usd = models.DecimalField(
        max_digits=8, decimal_places=4, default=Decimal("0.0000")
    )
    duration_seconds = models.FloatField(null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return f"{self.action_type} ({self.backend}): ${self.estimated_cost_usd}"


class TestRun(models.Model):
    """A differential test run for a PR (§9)."""

    RUN_TYPE_CHOICES = [
        ("pr_branch", "PR Branch"),
        ("base_cherry_pick", "Base + Cherry-Picked Tests"),
    ]

    STATUS_CHOICES = [
        ("pending", "Pending"),
        ("running", "Running"),
        ("completed", "Completed"),
        ("failed", "Failed"),
        ("timeout", "Timeout"),
    ]

    VERDICT_CHOICES = [
        ("good", "Good"),
        ("suspect", "Suspect"),
        ("broken", "Broken"),
        ("infra", "Infra"),
    ]

    pull_request = models.ForeignKey(
        PullRequest, on_delete=models.CASCADE, related_name="test_runs"
    )
    run_type = models.CharField(max_length=20, choices=RUN_TYPE_CHOICES)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="pending")
    test_scope = models.JSONField(default=list)
    results = models.JSONField(null=True, blank=True)
    differential_verdict = models.CharField(
        max_length=20, choices=VERDICT_CHOICES, null=True, blank=True
    )
    container_image = models.CharField(max_length=500, blank=True, default="")
    error_log = models.TextField(blank=True, default="")
    started_at = models.DateTimeField(null=True, blank=True)
    finished_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self) -> str:
        verdict = f" [{self.differential_verdict}]" if self.differential_verdict else ""
        return f"TestRun for {self.pull_request}{verdict}"


class AgentFeedback(models.Model):
    """Feedback sent to an AI agent session that created a PR (v1.25).

    Tracks structured feedback sent directly to Claude Code sessions
    or Codex tasks, as an alternative to posting GitHub comments.
    """

    ASSESSMENT_CHOICES = [
        ("good", "Good"),
        ("needs-work", "Needs Work"),
        ("reject", "Reject"),
    ]

    FEEDBACK_METHOD_CHOICES = [
        ("session-url", "Session URL"),
        ("github-comment", "GitHub Comment"),
    ]

    pull_request = models.ForeignKey(
        PullRequest, on_delete=models.CASCADE, related_name="agent_feedbacks"
    )
    assessment = models.CharField(max_length=20, choices=ASSESSMENT_CHOICES)
    feedback_body = models.TextField()
    feedback_method = models.CharField(
        max_length=20, choices=FEEDBACK_METHOD_CHOICES, default="session-url"
    )
    sent_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return f"Feedback for {self.pull_request}: {self.assessment}"
