"""Session link detection for AI-generated PRs (v1.25).

Pure-function module that parses PR descriptions to detect AI agent
session links (Claude Code, Codex, generic). No Django imports.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

# Patterns to detect in PR description, ordered by specificity.
# Each tuple: (compiled regex, agent_type)
SESSION_PATTERNS: list[tuple[re.Pattern[str], str]] = [
    # Claude Code
    (re.compile(r"Session:\s*(https://claude\.ai/code/session/\S+)", re.IGNORECASE), "claude-code"),
    (re.compile(r"claude[- ]code.*session[: ]+(https://\S+)", re.IGNORECASE), "claude-code"),
    # Codex
    (re.compile(r"Task ID:\s*(task_\S+)", re.IGNORECASE), "codex"),
    (re.compile(r"codex.*task[: ]+(\S+)", re.IGNORECASE), "codex"),
    # Generic: any URL in a "Generated by" block
    (re.compile(r"Generated by.*\n.*?(https://\S+)", re.IGNORECASE), "generic"),
]


@dataclass(frozen=True)
class SessionInfo:
    """Detected agent session from a PR description."""

    agent_source: str  # "claude-code", "codex", "generic"
    session_url: str  # URL for claude-code/generic, empty for codex
    task_id: str  # task ID for codex, empty otherwise


def detect_agent_session(body: str | None) -> SessionInfo | None:
    """Parse a PR description and return session info if an AI agent is detected.

    Returns the first match found. Returns None if no patterns match.
    """
    if not body:
        return None

    for pattern, agent_type in SESSION_PATTERNS:
        match = pattern.search(body)
        if match:
            value = match.group(1)
            if agent_type == "codex":
                return SessionInfo(
                    agent_source=agent_type,
                    session_url="",
                    task_id=value,
                )
            return SessionInfo(
                agent_source=agent_type,
                session_url=value,
                task_id="",
            )

    return None
